Repository redhat-developer/rhdh, pull requests merged in 2023-11, with the labels that each got.

#701 docs(app): add documentation for RBAC backend plugin
  .changeset/chilly-ghosts-own.md
  showcase-docs/getting-started.md
Labels: priority/critical

#720 feat(backend): add the remaining auth providers
  .changeset/swift-peas-act.md
  packages/backend/src/plugins/auth.ts
Labels: priority/critical

#602 feat(showcase): add conditional rendering for login page
  .changeset/tiny-cougars-unite.md
  packages/app/config.d.ts
  packages/app/src/App.tsx
  packages/app/src/api/AuthApiRefs.ts
  packages/app/src/api/CustomDataApiClient.ts
  packages/app/src/api/index.ts
  packages/app/src/apis.ts
  packages/app/src/components/DynamicRoot/defaultAppComponents.tsx
  packages/app/src/components/SignInPage/SignInPage.tsx
  packages/app/src/hooks/useQuickAccess.ts
  packages/app/src/lib/CustomTechRadar.ts
  showcase-docs/getting-started.md
Labels: priority/critical

#734 chore: add @janus-idp/backstage-plugin-acr...
  .changeset/sharp-walls-wait.md
  app-config.dynamic-plugins.yaml
  app-config.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
Labels: priority/critical

#744 chore: revert `yarn start` script
  packages/backend/package.json
Labels: cherry-pick-1.0.x

#749 fix: removes tekton tab
  .changeset/real-boxes-clap.md
  packages/app/src/components/catalog/EntityPage/index.tsx
  showcase-docs/dynamic-plugins.md
Labels: cherry-pick-1.0.x

#752 docs(dynamic-plugins): update and complete the docs
  .changeset/perfect-balloons-repeat.md
  showcase-docs/dynamic-plugins.md
Labels: cherry-pick-1.0.x

#738 fix: bring back responsive layout
  .changeset/hot-paws-grab.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  packages/app/config.d.ts
  packages/app/src/components/catalog/EntityPage/index.tsx
  packages/app/src/components/catalog/Grid/Grid.tsx
  packages/app/src/components/catalog/tab/tab.tsx
Labels: cherry-pick-1.0.x

#757 fix(rbac): add more static plugins to RBAC list
  .changeset/wild-planes-move.md
  packages/backend/src/index.ts
Labels: cherry-pick-1.0.x

#759 fix(topology): fix topology view layout
  .changeset/strong-flies-jam.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
Labels: cherry-pick-1.0.x

#736 feat(dynamic-plugins): replace static MUI Icons library import with dynamic appIcons
  .changeset/rotten-seas-fetch.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/src/index.ts
  packages/app/config.d.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  showcase-docs/dynamic-plugins.md
Labels: cherry-pick-1.0.x

#753 RHIDP-512 - adapt new helm chart
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-test/cypress/e2e/guest-signin-happy-path.spec.ts
Labels: cherry-pick-1.0.x

#742 fix: correctly use dynamic plugin config schemas
  .changeset/dull-hotels-dream.md
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-pagerduty/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/plugins/app.ts
  packages/backend/src/schemas.ts
  showcase-docs/dynamic-plugins.md
  yarn.lock
Labels: cherry-pick-1.0.x

#761 fix(rbac): update rbac-backend plugin to version 1.6.3
  .changeset/slimy-numbers-grab.md
  packages/backend/package.json
  yarn.lock
Labels: cherry-pick-1.0.x

#766 fix: increase max entry size for dynamic plugins
  docker/install-dynamic-plugins.py
Labels: cherry-pick-1.0.x

#751 update OIDC sign in page title
  .changeset/rotten-dolls-relate.md
  packages/app/src/components/SignInPage/SignInPage.tsx
Labels: cherry-pick-1.0.x

#765 fix(dynamic-frontend): loader code hardening
  .changeset/tasty-badgers-give.md
  package.json
  packages/app/src/components/DynamicRoot/DynamicRoot.test.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/catalog/tab/tab.tsx
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/utils/dynamicUI/bindAppRoutes.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/getMountPointData.ts
  packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
Labels: cherry-pick-1.0.x

#767 fix(logging): call toString method on UrlReader
  .changeset/fluffy-carpets-hug.md
  packages/backend/src/index.ts
Labels: cherry-pick-1.0.x

#769 chore: shell script to install dynamic plugins
  docker/Dockerfile
  docker/brew.Dockerfile
  docker/install-dynamic-plugins.sh
Labels: cherry-pick-1.0.x

#772 Change import of HostDiscovery
  .changeset/fresh-parrots-develop.md
  packages/backend/src/index.ts
Labels: cherry-pick-1.0.x

#773 fix: use the 'tar' filter to remove warnings (2)
  docker/install-dynamic-plugins.py
Labels: cherry-pick-1.0.x

#774 fix(dynamic-frontend): provide proper route bind targets
  .changeset/large-fans-grow.md
  packages/app/config.d.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.test.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/utils/dynamicUI/bindAppRoutes.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  showcase-docs/dynamic-plugins.md
Labels: cherry-pick-1.0.x

#778 bump base images to latest released versions
  docker/Dockerfile
  docker/brew.Dockerfile
Labels: cherry-pick-1.0.x, cherry-pick-OK

#740 Remove legacy `enabled.xxx` option
  .changeset/chatty-colts-cross.md
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  app-config.deprecated.yaml
  app-config.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/src/dynamic/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/src/dynamic/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/src/dynamic/index.ts
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/src/dynamic/index.ts
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/src/dynamic/index.ts
  packages/backend/src/index.ts
Labels: cherry-pick-1.0.x

#780 fix: add skipLibCheck and remove wrap-ansi resolution
  package.json
  tsconfig.json
  yarn.lock
Labels: cherry-pick-1.0.x

#793 fix(dynamic): fix possible dependency conflict
  .changeset/tall-pandas-enjoy.md
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-pagerduty/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  yarn.lock
Labels: cherry-pick-1.0.x

#797 chore: RHIDP-662 make the mkdocs executable...
  docker/brew.Dockerfile
Labels: cherry-pick-1.0.x

#798 chore(deps): Update aap, keycloak and ocm backends
  .changeset/seven-icons-jam.md
  dynamic-plugins/imports/package.json
Labels: cherry-pick-1.0.x

#735 docs: document monitoring and logging for openshift and AKS
  showcase-docs/configuration_files/ama-metrics-prometheus-config.yaml
  showcase-docs/configuration_files/ama-metrics-settings-configmap.yaml
  showcase-docs/configuration_files/container-azm-ms-agentconfig.yaml
  showcase-docs/getting-started.md
  showcase-docs/images/openshift-metrics.png
  showcase-docs/monitoring-and-logging.md
Labels: cherry-pick-1.0.x

#807 fix: remove segment plugin
  .changeset/warm-papayas-sparkle.md
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  README.md
  app-config.example.yaml
  app-config.yaml
  packages/app/package.json
  packages/app/src/apis.ts
  showcase-docs/getting-started.md
  yarn.lock
Labels: cherry-pick-1.0.x

#808 feat: add scaffolder actions plugins
  .changeset/pretty-trainers-appear.md
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
Labels: cherry-pick-1.0.x

#809 fix: update keycloak plugin to fix not a constructor error
  .changeset/shy-berries-confess.md
  dynamic-plugins/imports/package.json
Labels: cherry-pick-1.0.x

#810 feat: add 3scale plugin
  .changeset/rare-roses-attack.md
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
Labels: cherry-pick-1.0.x

#812 fix(dynamic-plugins): use segment as a dynamic plugin
  .changeset/new-adults-sort.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
Labels: cherry-pick-1.0.x

#814 fix: typo in backend package names missing -dynamic suffix
  dynamic-plugins.default.yaml
Labels: cherry-pick-1.0.x

#822 fix: missing .npm directory in Brew build
  docker/brew.Dockerfile
Labels: cherry-pick-1.0.x
