Repository redhat-developer/rhdh, pull requests merged in 2024-02, with the labels that each got.

#681 feat(bitbucket): add discovery support for bitbucket (server & cloud)
  .changeset/small-rabbits-tan.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/.eslintignore
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/.eslintrc.js
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/src/alpha.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/src/dynamic/alpha.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/src/dynamic/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/.eslintignore
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/.eslintrc.js
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/src/alpha.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/src/dynamic/alpha.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/src/dynamic/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/src/index.ts
  yarn.lock
Labels: approved, lgtm

#943 fix(script): fix the upgrade script
  scripts/update-backstage.mjs
Labels: approved, lgtm

#947 fix: downgrade ArgoCD frontend plugin, upstream regression
  .changeset/smooth-pumas-argue.md
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
Labels: approved, lgtm

#937 feat(rbac): add rbac dynamic plugin
  .changeset/neat-sloths-add.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#942 [Automation] Migrate and enable github happy path flow test case
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/support/testData/resources.ts
  e2e-tests/playwright/utils/APIHelper.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/tsconfig.json
Labels: approved, lgtm

#948 fix(3scale): modify 3scale environment variables
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#945 chore: move helm-backstage repo to redhat-developer/rhdh-chart
  showcase-docs/dynamic-plugins.md
  showcase-docs/monitoring-and-logging.md
Labels: approved, lgtm

#951 fix(3scale): modify 3scale environment variables - using THREESCALE
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#932 feat(app) an AdminPage for admin plugins
  .changeset/young-numbers-whisper.md
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/admin/AdminPage.test.tsx
  packages/app/src/components/admin/AdminPage.tsx
Labels: approved, lgtm

#952 docs: update `Installing a dynamic plugin package in the showcase` section
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#955 feat(AdminPage): support full page components
  .changeset/strange-sheep-obey.md
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  packages/app/src/components/admin/AdminPage.tsx
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#935 [Test automation] Verify Azure Container Registry plugin is supported
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#961 chore(app): remove deprecation warning
  .changeset/twenty-falcons-work.md
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
Labels: approved, lgtm

#964 chore(deps): updates topology and tekton plugin
  .changeset/short-fans-stare.md
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#962 docs(customization): added support configuration guide
  showcase-docs/customization.md
  showcase-docs/images/example-support-button.png
  showcase-docs/images/support-not-configured.png
Labels: approved, lgtm

#967 Update PR Check Pipeline for Conditional Image Build wait handling, Excluding '.ibm' and 'e2e-tests' Directories
  .ibm/pipelines/openshift-tests.sh
Labels: approved, lgtm

#954 [e2e-tests] enable and migrate e2e-test ocm, dynamic plugins info.
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/support/pages/Clusters.ts
  e2e-tests/playwright/support/testData/dynamic-plugins-info.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#965 chore(rbac): bump up rbac plugin package version
  .changeset/two-needles-sniff.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#975 [e2e-tests] Update and Fix tests (ocm & dynamic plugins info)
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/support/testData/dynamic-plugins-info.ts
Labels: approved, lgtm

#970 chore: update links on homepage
  .changeset/smart-dolphins-chew.md
  packages/app/public/homepage/data.json
Labels: approved, lgtm

#959 docs: Document how to set up monitoring and logging on OpenShift when using the operator
  showcase-docs/monitoring-and-logging.md
Labels: approved, lgtm

#977 fix(plugins): fix plugin wrapper yarn locks
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
Labels: approved, lgtm

#976 chore: add action to cleanup github action cache
  .github/workflows/cache-cleanup.yaml
Labels: approved, lgtm

#983 chore(ci): remove caching from docker builds
  .github/actions/docker-build/action.yaml
Labels: approved, lgtm

#960 Add MUI theme config to fix Sidebar and Tabs color
  .changeset/sweet-colts-exercise.md
  packages/app/src/components/Root/Root.tsx
  packages/app/src/themes/componentOverrides.ts
  packages/app/src/themes/darkTheme.ts
  packages/app/src/themes/lightTheme.ts
Labels: approved, lgtm

#957 fix(ui): add pf5 button style config
  .changeset/strange-zebras-complain.md
  packages/app/src/themes/componentOverrides.ts
  packages/app/src/themes/darkTheme.ts
  packages/app/src/themes/defaultThemePalette.ts
  packages/app/src/themes/lightTheme.ts
Labels: approved, lgtm

#958 [Test automation] Sign in using Google as authentication provider RHIDP-758
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#984 Fix MUI Tab console warnings
  .changeset/good-kings-allow.md
  packages/app/src/themes/componentOverrides.ts
Labels: approved, lgtm

#909 chore: refresh helm chart README; fix broken...
  showcase-docs/helm-chart.md
Labels: approved, lgtm

#988 Add test log as an PR comment when backstage instance is not up/running
  .ibm/pipelines/openshift-tests.sh
Labels: lgtm

#991 chore(deps): upgrade to backstage 1.23.1
  backstage.json
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#973 feat: enable techdocs by default
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  dynamic-plugins.default.yaml
  e2e-tests/playwright/e2e/techdocs.spec.ts
Labels: approved, lgtm

#904 RHIDP-1074 [Playwright tests] enable quay.spec.ts test
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#995 [e2e-test] Enhance loginAsGithubUser() to Handle Intermittent Pop-up Visibility Issues & Fix Quay test
  .ibm/pipelines/openshift-tests.sh
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#989 fix(admin): added RBAC tab display condition
  packages/app/package.json
  packages/app/src/components/admin/AdminPage.tsx
  packages/app/src/components/admin/AdminTabs.test.tsx
  packages/app/src/components/admin/AdminTabs.tsx
  yarn.lock
Labels: approved, lgtm, cherry-pick-1.1.x

#998 fix(rbac): added unit test for AdminPage
  packages/app/src/components/admin/AdminPage.test.tsx
Labels: approved, lgtm

#1006 [Test infra] Enable manual trigger of e2e test
  .ibm/pipelines/functions.sh
Labels: approved, lgtm

#981 [rbac]: added playwright e2e tests
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/techdocs.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/support/pageObjects/page-obj.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1022 fix(scripts): add prettier step to update script
  scripts/update-backstage.mjs
Labels: approved, lgtm

#1026 [rbac]: enable skipped e2e tests
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
Labels: approved, lgtm

#1031 chore(ci): remove renovate workflow and separate python/js PRs
  .changeset/good-kings-allow.md
  .changeset/renovate-7ac6d40.md
  .changeset/renovate-d0459eb.md
  .changeset/strange-zebras-complain.md
  .github/renovate.json
  .github/workflows/sync-renovate-changeset.yaml
Labels: approved, lgtm

#1044 chore(deps): update packages
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#846 RHIDP-777 [Test automation] Verify Tekton is a supported plugin
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/pipeline-run/hello-world-pipeline-run.yaml
  .ibm/pipelines/resources/pipeline-run/hello-world-pipeline.yaml
  .ibm/pipelines/resources/pipeline-run/pipelines-operator.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
  e2e-tests/playwright/e2e/techdocs.spec.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/tekton/tekton.ts
Labels: approved, lgtm

#1047 Update testCluster specifications and enable OCM test
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
Labels: approved, lgtm
