Repository redhat-developer/rhdh, pull requests merged in 2024-05, with the labels that each got.

#1202 feat(admin): identify external plugins
  .sonarcloud.properties
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/__fixtures__/listLoadedPluginsResult.ts
  plugins/dynamic-plugins-info/src/api/types.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: lgtm

#1223 feat: tagRelease.sh bump versions in 1.1.x for 1.1 release
  e2e-tests/package.json
  package.json
  packages/app/src/build-metadata.json
Labels: lgtm

#1227 chore: move updateBuildMetadata into its own...
  .husky/pre-commit
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  package.json
  packages/app/src/build-metadata.json
  scripts/update-backstage.mjs
  scripts/update-metadata.mjs
Labels: approved, lgtm

#1228 chore: remove ansi colors from logs
  packages/backend/src/logger/customLogger.ts
Labels: approved, lgtm

#1216 Update playwright config and enable screenshots and video recording for serial tests
  .ibm/pipelines/functions.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/openshift-tests.sh
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1230 add a missing condition check for the nightly rbac test
  .ibm/pipelines/openshift-ci-tests.sh
Labels: lgtm

#1233 move .eslintrc.js to .eslintrc to fix issues...
  .eslintrc
  .eslintrc.js
  .husky/pre-commit
  .prettierignore
  packages/app/src/build-metadata.json
  scripts/update-backstage.mjs
  scripts/update-metadata.mjs
Labels: approved, lgtm

#1224 chore(renovate): automerge devdependencies
  .github/renovate.json
Labels: approved, lgtm

#1167 feat(deps): replace bundled themes with RHDH theme
  packages/app/package.json
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/Loader.tsx
  packages/app/src/components/DynamicRoot/defaultThemes.tsx
  packages/app/src/hooks/useUpdateTheme.test.ts
  packages/app/src/hooks/useUpdateTheme.ts
  packages/app/src/themes/darkTheme.ts
  packages/app/src/themes/lightTheme.ts
  yarn.lock
Labels: approved, lgtm

#1226 fix(ui): RHIDP-2044 enable frontend plugin loading
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info-backend.spec.ts
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/modules/authProvidersModule.ts
  plugins/dynamic-plugins-info-backend/package.json
  plugins/dynamic-plugins-info-backend/src/plugin.ts
  plugins/dynamic-plugins-info-backend/src/service/router.test.ts
  plugins/dynamic-plugins-info-backend/src/service/router.ts
  plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts
  plugins/dynamic-plugins-info/src/plugin.ts
  plugins/scalprum-backend/src/plugin.ts
  showcase-docs/auth.md
  yarn.lock
Labels: approved, lgtm

#1238 [e2e] update google authentication credentials from ci vault
  .ibm/pipelines/env_variables.sh
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Labels: approved, lgtm, ok-to-test

#1229 feat(admin): extended e2e tests
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
Labels: approved, lgtm

#1208 RHIDP-428 Send PR test results to ReportPortal
  .ibm/images/Dockerfile
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/data_router/data_router_metadata_template.json
Labels: approved, lgtm

#1235 [Test automation] re-enable the skipped e2e tests
  .ibm/pipelines/README.md
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/cluster_role/cluster-role-ocm.yaml
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Labels: approved, lgtm

#1251 Skip google-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Labels: approved, lgtm

#1249 fix(ui): RHIDP-2297 avoid duplicate config
  packages/app/src/components/DynamicRoot/DynamicRoot.test.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/ScalprumRoot.tsx
  packages/app/src/components/admin/AdminTabs.test.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
Labels: approved, lgtm

#1253 feat(app) RHIDP-1803 enable field extensions
  packages/app/package.json
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/test/TestRoot.tsx
  showcase-docs/dynamic-plugins.md
  yarn.lock
Labels: approved, lgtm

#1252 chore(deps): update RHDH theme
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1254 RHIDP-428 RP Fix nightly URL and hostnames to secrets
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1257 feat(catalog): added created at column in the catalog page
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  packages/app/src/components/AppBase/AppBase.tsx
  packages/backend/package.json
  packages/backend/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1259 [e2e] fix: add google 2fa and re-enable test
  .ibm/pipelines/env_variables.sh
  e2e-tests/package-lock.json
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/yarn.lock
Labels: approved, lgtm

#1260 [e2e] Delete wrongly created e2e-tests/package-lock.json
  e2e-tests/package-lock.json
  e2e-tests/yarn.lock
Labels: approved, lgtm

#1262 fix(app-backend): restore external config...
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  package.json
  patches/@backstage+plugin-app-backend+0.3.65.patch
  yarn.lock
Labels: approved, lgtm

#1263 fix(app-backend): part 2 - restore external...
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  patches/@backstage+plugin-app-backend+0.3.65.patch
Labels: approved

#1261 [QE] Automate Scenario - Add timestamps to templates
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1028 feat: configure Segment plugin to be able to send data to Red Hat (enabled by default)
  .ibm/images/Dockerfile
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  dynamic-plugins.default.yaml
  showcase-docs/getting-started.md
Labels: approved, lgtm

#1225 feat(backend): Support running behind a corporate proxy [RHIDP-2217]
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docs/proxy.md
  packages/backend/package.json
  packages/backend/src/corporate-proxy.ts
  packages/backend/src/index.ts
  showcase-docs/corporate-proxy.md
  yarn.lock
Labels: approved, lgtm

#1269 chore(rbac): update rbac and rbac-backend plugin versions
  dynamic-plugins/imports/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1266 RHIDP-2069 - [QE] Automate Scenario - Include HTTP Request as pre-loaded Plugin to RHDH
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
Labels: approved, lgtm

#1273 Automate E2E Testing for Multiple OCP Versions in Nightly Build
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/support/pages/Clusters.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1277 chore(docker): set the `NODE_OPTIONS=--no-node-snapshot` env variable
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: lgtm

#1280 [e2e] add custom theme test automation
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/.gitignore
  e2e-tests/playwright/e2e/custom-theme.spec.ts
Labels: approved, lgtm

#1245 fix(app): RHIDP-2266 add condition error handling
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/catalog/EntityPage/DynamicEntityTab.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/getMountPointData.ts
Labels: approved, lgtm

#1292 RHIDP-2067 [QE] Automate Scenario - Support external postgres databases
  .ibm/manual-tests/postgres/README.md
  .ibm/manual-tests/postgres/install.sh
  .ibm/manual-tests/postgres/postgres-crt-secrets.yaml
  .ibm/manual-tests/postgres/postgress-cred-secret.yaml
  .ibm/manual-tests/postgres/values.yaml
Labels: approved, lgtm
