Repository redhat-developer/rhdh, pull requests merged in 2024-09, with the labels that each got.

#1535 [Test automation] allow users to customize tab icon
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/support/testData/custom-theme.ts
Labels: approved, lgtm

#1547 [1.3.x] add bulk import plugin
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1519 dynamic plugins cache
  docker/install-dynamic-plugins.py
Labels: approved, lgtm

#1555 ci: Configure and Enable PR check and Nightly e2e job for Branch 1.3.x
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/package.json
Labels: approved, lgtm

#1559 chore(deps): update argocd plugin version
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  yarn.lock
Labels: lgtm

#1561 add dynamic wrapper for ping identity plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1558 remove static installation of plugin-catalog-backend-module-logs
  packages/backend/package.json
  packages/backend/src/index.ts
Labels: approved, lgtm

#1527 fix(pagerduty): add dynamic plugin wrapper for backend plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/.eslintignore
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1507 feat(nav): add support for nested nav
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/UIhelper.ts
  packages/app/src/App.tsx
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/DynamicRoot/CommonIcons.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/DynamicRoot/ScalprumRoot.tsx
  packages/app/src/components/Root/MenuIcon.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/admin/AdminPage.test.tsx
  packages/app/src/components/admin/AdminPage.tsx
  packages/app/src/components/admin/AdminTabs.test.tsx
  packages/app/src/components/admin/AdminTabs.tsx
  packages/app/src/components/catalog/EntityPage/ContextMenuAwareEntityLayout.tsx
  packages/app/src/components/search/SearchPage.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
  packages/app/src/utils/test/TestRoot.tsx
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoPage.tsx
  plugins/dynamic-plugins-info/src/index.ts
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#1579 fix entityRef name when signing in without user in catalog
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1577 chore(deps): update rbac backend and scaffolder module annotator versions
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1582 fix CVE-2024-45590
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1571 [Test automation] make branding icons and primary color configurable
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/support/testData/custom-theme.ts
Labels: approved, lgtm

#1536 update getting started docs
  showcase-docs/getting-started.md
Labels: approved, lgtm

#1585 fix: do not populate dynamic-plugins-root directory in the container image
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docker/prow.Dockerfile
Labels: approved, lgtm

#1589 upgrade GH plugin support to prod
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
Labels: approved, lgtm

#1565 Add RBAC file watcher and alias tests
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1578 feat(ui): enable customization of static items in sidebar menu
  packages/app/src/App.tsx
  packages/app/src/components/DynamicRoot/CommonIcons.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/consts.ts
  showcase-docs/customization.md
Labels: approved, lgtm

#1596 [e2e] Fix failure of `catalog-timestamp`
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
Labels: approved, lgtm

#1581 update bulk-import version
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1599 chore(issue tracking): direct people to report janus plugin issues in JIRA, not BCP (RHIDP-3678)
  .github/ISSUE_TEMPLATE/config.yml
Labels: lgtm

#1601 chore(deps): update github-pull-requests plugin version
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
Labels: approved, lgtm

#1603 fix(ui): allow empty string icon in menu item
  packages/app/src/components/Root/Root.tsx
Labels: approved, lgtm

#1576 [e2e] Switch `droute` pod for RP and update
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/data_router/data_router_metadata_template.json
Labels: approved, lgtm, do-not-merge/hold

#1605 chore(deps): bump bulk-import plugins
  dynamic-plugins/imports/package.json
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Labels: approved, lgtm

#1595 revert enabling dangerouslyAllowSignInWithoutUserInCatalog for GitHub
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1618 chore(deps): bump bulk import backend plugin to 1.5.2
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1594 move @janus-idp/cli to devDependency in ping identity plugin
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  yarn.lock
Labels: approved, lgtm

#1614 chore(deps): bump ocm-backend
  dynamic-plugins/imports/package.json
Labels: approved

#1623 fix(ui): updated menu item key and path mapping logic
  packages/app/src/components/Root/Root.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#1626 chore(deps): bump bulk import frontend plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1615 fix(app): proxy for home and learning paths
  packages/app/src/api/CustomDataApiClient.ts
  packages/app/src/apis.ts
Labels: approved, lgtm

#1640 [1.3.x] Fix e2e-tests ci and test issues
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
Labels: approved, lgtm

#1631 chore: Upgrade rhdh theme package version
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#1627 [1.3.x] chore(deps): bump bulk import frontend plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1608 Configure primary color 1.3.x
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/support/testData/custom-theme.ts
Labels: approved, lgtm

#1637 [1.3.x] manual cherrypick #1527 add pagerduty dynamic backend
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/.eslintignore
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1463 docs(audit-log): add additional disclaimers to audit log docs
  showcase-docs/audit-log.md
Labels: approved, lgtm

#1609 [e2e] Fix occasional failure of `ocm` test and skip `keycloak` test
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
Labels: approved

#1650 chore(owners): update approvers
  OWNERS
Labels: approved, lgtm

#1636 chore(deps): 1.3.x fix fix CVE-2024-45590, CVE-2024-43799, CVE-2024-45296
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
  packages/backend/package.json
  plugins/auth-backend-module-oidc-provider/package.json
  plugins/dynamic-plugins-info-backend/package.json
  plugins/licensed-users-info-backend/package.json
  plugins/scalprum-backend/package.json
  yarn.lock
Labels: approved, lgtm

#1635 chore(deps): bump bulk-import-backend-plugin to 1.5.3
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1632 chore(msg): update sign-in error message
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1652 chore(deps): bump up keycloak-backend
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1628 chore(deps): bump tekton and quay plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1633 chore(deps): bump argocd and argocd-common plugins
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#1634 [1.3.x] chore(deps): bump argocd and argocd-common plugins
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#1648 chore(deps): bump rbac plugin
  dynamic-plugins/imports/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1629 [1.3.x] chore(deps): bump tekton and quay plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1657 [1.3.x] manual cherry-pick to update `droute` and switch back to `pr-os` cluster
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/data_router/data_router_metadata_template.json
Labels: approved, lgtm

#1588 chore(e2e): Automate Bulk import from Git
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/BulkImport.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/support/testData/BulkImport.ts
  e2e-tests/playwright/utils/APIEndpoints.ts
  e2e-tests/playwright/utils/APIHelper.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1658 [1.3.x] chore(deps): bump rbac plugin
  dynamic-plugins/imports/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1604 [1.3.x] manual cherrypick for 1565 and 1596
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, ok-to-test

#1662 chore(deps): update plugins to mirror 1.3.x plugins branch
  dynamic-plugins/imports/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#1630 [1.3.x] manual cherrypick #1577 update rbac and scaffolder module annotator
  packages/backend/package.json
  yarn.lock
Labels: approved

#1532 RHIDP-3816: feat(homepage): enable plugins to extend the homepage
  .dockerignore
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  packages/app/package.json
  packages/app/public/homepage/README.md
  packages/app/src/App.tsx
  packages/app/src/api/LearningPathApiClient.ts
  packages/app/src/api/index.ts
  packages/app/src/apis.ts
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/components/learningPaths/LearningPathsPage.tsx
  packages/app/src/hooks/useLearningPathData.test.ts
  packages/app/src/hooks/useLearningPathData.ts
  packages/app/src/types/types.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
  packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
  plugins/dynamic-home-page/.eslintrc.js
  plugins/dynamic-home-page/README.md
  plugins/dynamic-home-page/app-config.janus-idp.yaml
  plugins/dynamic-home-page/dev/index.tsx
  plugins/dynamic-home-page/dev/quickaccess-default.json
  plugins/dynamic-home-page/package.json
  plugins/dynamic-home-page/src/api/QuickAccessApiClient.ts
  plugins/dynamic-home-page/src/api/index.ts
  plugins/dynamic-home-page/src/components/DynamicHomePage.tsx
  plugins/dynamic-home-page/src/components/Headline.tsx
  plugins/dynamic-home-page/src/components/Markdown.tsx
  plugins/dynamic-home-page/src/components/MarkdownCard.tsx
  plugins/dynamic-home-page/src/components/Placeholder.tsx
  plugins/dynamic-home-page/src/components/QuickAccessCard.tsx
  plugins/dynamic-home-page/src/components/ReadOnlyGrid.tsx
  plugins/dynamic-home-page/src/components/SearchBar.tsx
  plugins/dynamic-home-page/src/defaults.ts
  plugins/dynamic-home-page/src/hooks/useHomePageMountPoints.ts
  plugins/dynamic-home-page/src/hooks/useQuickAccessLinks.test.ts
  plugins/dynamic-home-page/src/hooks/useQuickAccessLinks.ts
  plugins/dynamic-home-page/src/index.ts
  plugins/dynamic-home-page/src/plugin.test.ts
  plugins/dynamic-home-page/src/plugin.ts
  plugins/dynamic-home-page/src/routes.ts
  plugins/dynamic-home-page/src/setupTests.ts
  plugins/dynamic-home-page/src/types.ts
  plugins/dynamic-home-page/turbo.json
  plugins/dynamic-plugins-info/app-config.janus-idp.yaml
  yarn.lock
Labels: approved, lgtm

#1611 [1.2.x] [e2e] cherry-pick #1576, #1609, `catalog-timestamp` fix
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/data_router/data_router_metadata_template.json
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1665 fix: accomodate the move of `resolvePackagePath` from `backend-common ` to `backend-plugin-api`.
  packages/backend/src/loader/CommonJSModuleLoader.ts
Labels: approved, cherry-pick-release-1.3

#1671 fix(app): update cli for singleton config
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-logs/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1675 Temp change to enable e2e on release-1.3
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1673 [release-1.3] fix(app): update cli for singleton config
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-logs/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1678 chore(deps): bump to the upversioned janus-idp/cli 1.14.0 (should be same as 1.13.2 but bumped in main to allow patches in release-1.3 branch)
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-logs/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1638 add documentation and script to set up PingIdentity env for testing
  docs/provider-setup/ping-identity-env-setup.md
  docs/provider-setup/resources/ping-identity-grant-app-roles.png
  mkdocs.yaml
  scripts/ping-identity-setup/ping-identity-secrets.env
  scripts/ping-identity-setup/ping-identity-setup.sh
Labels: approved, lgtm

#1672 RHIDP-3063 - [QE] Make the sidebar navigation configuration defined
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/learning-path-page.spec.ts
  e2e-tests/playwright/e2e/plugins/frontend/sidebar.spec.ts
  e2e-tests/playwright/e2e/techdocs.spec.ts
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1659 [1.3.x] [e2e-tests] manual cherrypick for 1588
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/BulkImport.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/support/testData/BulkImport.ts
  e2e-tests/playwright/utils/APIEndpoints.ts
  e2e-tests/playwright/utils/APIHelper.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm, ok-to-test, cherry-pick-release-1.3

#1689 [WIP] deps(homepage): update upstream home plugin dependencies
  plugins/dynamic-home-page/package.json
  yarn.lock
Labels: do-not-merge/work-in-progress

#1681 Enabling keycloak tests again
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
Labels: approved, lgtm

#1692 refactor(backend): remove deprecated calls from healthcheck and metrics
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/metrics.ts
  packages/backend/src/modules/healthcheck.ts
  packages/backend/src/modules/index.ts
  packages/backend/src/modules/metrics.ts
Labels: approved, lgtm

#1697 fix(argocd): generate frontend plugin assets for argocd plugin
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
Labels: approved, lgtm

#1699 fix(argocd): remove dist-dynamic folder
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1472 RHIDP-2128 [Test automation] Establish AKS nightly tests
  .ibm/images/Dockerfile
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Labels: approved, lgtm

#1701 chore: add wrapper for acr plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-acr/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1705 chore(deps): bump to body-parser@^1.20.3
  package.json
  yarn.lock
Labels: approved, lgtm

#1707 chore(deps): bump to body-parser@^1.20.3
  package.json
  yarn.lock
Labels: approved, lgtm

#1709 chore(e2e): fix configuration to reflect changes from #1701
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
Labels: approved, lgtm

#1706 Cleanup docs directories
  docs/application-migration/checklist-for-building-containers.md
  docs/application-migration/high-level-onboarding-process.png
  docs/application-migration/learning-path-for-developers.md
  docs/application-migration/migration-process-overview.md
  docs/application-migration/migration-process-steps.md
  docs/audit-log.md
  docs/auth.md
  docs/configuration_files/ama-metrics-prometheus-config.yaml
  docs/configuration_files/ama-metrics-settings-configmap.yaml
  docs/configuration_files/container-azm-ms-agentconfig.yaml
  docs/corporate-proxy.md
  docs/customization.md
  docs/dynamic-plugins.md
  docs/helm-chart.md
  docs/images/custom-title-and-favicon.png
  docs/images/default-collapsed-icon.png
  docs/images/default-expanded-logo.png
  docs/images/example-dark-mode-banner.png
  docs/images/example-dark-mode-primary-color.png
  docs/images/example-light-mode-banner.png
  docs/images/example-light-mode-primary-color.png
  docs/images/example-sidebar-indicator-dark.png
  docs/images/example-sidebar-indicator-light.png
  docs/images/example-support-button.png
  docs/images/openshift-metrics.png
  docs/images/ping-identity-grant-app-roles.png
  docs/images/support-not-configured.png
  docs/index.md
  docs/monitoring-and-logging.md
  docs/ping-identity-env-setup.md
  mkdocs.yaml
  showcase-docs/getting-started.md
Labels: approved, lgtm

#1625 [e2e][RHIDP-754] Github discovery UI test
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/github-discovery.spec.ts
  e2e-tests/playwright/support/api/github-structures.ts
  e2e-tests/playwright/support/api/github.ts
  e2e-tests/playwright/support/pages/Catalog.ts
  e2e-tests/playwright/support/pages/catalog-item.ts
  e2e-tests/playwright/utils/constants.ts
Labels: approved, lgtm, ok-to-test

#1710 [Topology]: remove custom resources from k8s configuration
  dynamic-plugins.default.yaml
Labels: approved, lgtm
