Repository redhat-developer/rhdh, pull requests merged in 2024-06, with the labels that each got.

#1285 chore: adding options to keep legacy behavior in export-dynamic script
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
Labels: approved, lgtm

#1284 chore(deps): update RHDH theme
  packages/app/package.json
  packages/app/src/components/admin/AdminTabs.tsx
  packages/app/src/themes/componentOverrides.ts
  packages/app/src/themes/defaultThemePalette.ts
  packages/app/src/themes/pageTheme.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  yarn.lock
Labels: approved, lgtm

#1290 feat(app) RHIDP-2338 expose dynamic UI config
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/DynamicRoot/ScalprumRoot.tsx
  packages/app/src/utils/dynamicUI/getMountPointData.ts
Labels: approved, lgtm

#1298 feat: support catalog entity extra context menu items.
  packages/app/src/components/catalog/EntityPage/ContextMenuAwareEntityLayout.tsx
  packages/app/src/components/catalog/EntityPage/EntityPage.tsx
Labels: approved, lgtm

#1282 chore: add patches for scaffolder audit logging with scaffolder permissions
  packages/backend/package.json
  patches/@backstage+plugin-catalog+1.19.0.patch
  patches/@backstage+plugin-scaffolder+1.19.3.patch
  patches/@backstage+plugin-scaffolder-backend+1.22.5.patch
  patches/@backstage+plugin-scaffolder-common+1.5.1.patch
  patches/@backstage+plugin-scaffolder-node+0.4.3.patch
  patches/@backstage+plugin-scaffolder-react+1.8.4.patch
  yarn.lock
Labels: approved, lgtm

#1299 feat: add the scaffolder relation processor plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
Labels: approved, lgtm

#1309 chore(auth): make oidc auth provider resolvers configurable
  .gitignore
  packages/backend/src/modules/authProvidersModule.ts
  plugins/auth-backend-module-oidc-provider/config.d.ts
  plugins/auth-backend-module-oidc-provider/package.json
  plugins/auth-backend-module-oidc-provider/src/module.ts
  plugins/auth-backend-module-oidc-provider/src/resolvers.ts
  showcase-docs/auth.md
  yarn.lock
Labels: approved, lgtm

#1308 Fixed broken links to plugins in main README.md file
  README.md
Labels: approved, lgtm, ok-to-test

#1312 chore(deps): update topology plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1311 RHDH pre-submit and post-submit job for 1.2.x
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  e2e-tests/package.json
Labels: approved, lgtm

#1317 chore: updates from privacy-legal team RHIDP-58
  showcase-docs/getting-started.md
Labels: lgtm

#1323 chore(deps): remove express 4.18 in favour...
  yarn.lock
Labels: approved, lgtm

#1326 chore(auth): add default resolver for OIDC auth provider
  packages/backend/src/modules/authProvidersModule.ts
  patches/@backstage+plugin-auth-node+0.4.12.patch
  showcase-docs/auth.md
Labels: approved, lgtm

#1335 fix(auth): fix deprecation warning when OIDC provider is configured
  packages/app/src/apis.ts
Labels: approved, lgtm

#1339 chore(renovate): separate test and dev deps, disable backstage updates
  .github/renovate.json
Labels: approved, lgtm

#1345 deps: update ws dependency in yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1332 Updated the label and container port in doc on Setting up Metrics Mon…
  showcase-docs/monitoring-and-logging.md
Labels: lgtm, ok-to-test

#1351 chore(deps): update yarn.lock to resolve CVE-2024-35255
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: kind/security, approved, lgtm

#1353 chore(renovate): rework config to break down PRs
  .github/renovate.json
Labels: approved, lgtm

#1352 add dynamic wrapper for msgraph plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/src/index.ts
  yarn.lock
Labels: approved, lgtm
