Repository redhat-developer/rhdh, pull requests merged in 2024-04, with the labels that each got.

#1150 chore(deps): fix tests (1.1.x)
  packages/app/src/themes/componentOverrides.ts
  yarn.lock
Labels: approved, lgtm

#1153 chore(renovate): update renovate config
  .github/renovate.json
Labels: approved, lgtm

#1163 Update and Deploy Custom Playwright Image for OpenShift CI Integration
  .ibm/images/Dockerfile
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1165 Update E2E Dockerfile to Include EOF
  .ibm/images/Dockerfile
Labels: approved, lgtm

#1151 feat(app): add static dynamic-plugins-info
  .dockerignore
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
  plugins/dynamic-plugins-info/.eslintrc.js
  plugins/dynamic-plugins-info/CONTRIBUTING.md
  plugins/dynamic-plugins-info/README.md
  plugins/dynamic-plugins-info/app-config.janus-idp.yaml
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/images/screenshot-plugin-list.png
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/__fixtures__/listLoadedPluginsResult.ts
  plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts
  plugins/dynamic-plugins-info/src/api/types.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
  plugins/dynamic-plugins-info/src/index.ts
  plugins/dynamic-plugins-info/src/plugin.test.ts
  plugins/dynamic-plugins-info/src/plugin.ts
  plugins/dynamic-plugins-info/src/routes.ts
  plugins/dynamic-plugins-info/src/setupTests.ts
  plugins/dynamic-plugins-info/tsconfig.json
  plugins/dynamic-plugins-info/turbo.json
  showcase-docs/dynamic-plugins.md
  yarn.lock
Labels: approved, lgtm

#1090 chore(rbac): update e2e test for bug fix
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1155 fix(ui): match table styles with PF5
  packages/app/src/themes/componentOverrides.ts
  packages/app/src/themes/defaultThemePalette.ts
Labels: approved, lgtm

#1105 docs: Update Showcase Dynamic plugins documentation to remove the part related to the old backend system
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#1055 Updated how OAuth headers are processed
  docs/configuration-env-variables.md
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1175 chore(deps): fail the build if workspace dirty after a yarn install (yarn.lock changed) (RHIDP-1203, RHIDP-1204)
  .github/workflows/ci.yaml
  .github/workflows/techdocs.yaml
Labels: lgtm

#1174 chore(deps): fail the build if workspace dirty after a yarn install (yarn.lock changed) (RHIDP-1203, RHIDP-1204)
  .github/workflows/ci.yaml
  .github/workflows/techdocs.yaml
  yarn.lock
Labels: approved, lgtm

#1172 feat(audit log): add audit log event stream
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/logger/customLogger.ts
  packages/backend/src/logger/index.ts
  yarn.lock
Labels: approved, lgtm

#1168 fix(template): fixed template cards display issues
  packages/app/src/themes/componentOverrides.ts
Labels: approved

#1171 fix(ui): match styles with PF5
  packages/app/src/themes/componentOverrides.ts
  packages/app/src/themes/darkTheme.ts
  packages/app/src/themes/defaultThemePalette.ts
  packages/app/src/themes/lightTheme.ts
Labels: approved, lgtm

#1186 RHIDP-1682 [Test automation] re-enable the skipped e2e tests #1148
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-k8s.yaml
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/deployment/deployment-test-app-component.yaml
  .ibm/pipelines/resources/service_account/service-account-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/support/pages/HomePage.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1193 Add ansible learning paths
  packages/app/public/learning-paths/data.json
Labels: approved, lgtm, needs-ok-to-test

#1211 chore(audit): update audit log format to json
  packages/backend/src/logger/customLogger.ts
Labels: approved, lgtm

#1207 RHIDP-1478: Include HTTP Request as pre-loaded Plugin to RHDH
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/.eslintrc.js
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/src/index.ts
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/src/plugin.ts
  yarn.lock
Labels: approved, lgtm

#1215 chore(owners): add NA roster
  OWNERS
Labels: approved, lgtm

#1204 branding: add ability to customize sidebar logo
  app-config.yaml
  packages/app/config.d.ts
  packages/app/src/components/Root/SidebarLogo.test.tsx
  packages/app/src/components/Root/SidebarLogo.tsx
  showcase-docs/customization.md
Labels: approved, lgtm

#1195 fix(ui): display issues
  packages/app/src/themes/componentOverrides.ts
Labels: approved, lgtm

#1213 fix(ui): tabs indicator display
  packages/app/src/themes/componentOverrides.ts
Labels: approved, lgtm

#1217 add additional approvers for OpenShift-CI-related changes
  OWNERS
Labels: approved, lgtm

#1184 feat(app): make learning paths configurable
  packages/app/src/api/CustomDataApiClient.ts
  packages/app/src/components/home/HomePage.tsx
  packages/app/src/components/learningPaths/LearningPathsPage.tsx
  packages/app/src/hooks/useCustomizationData.test.ts
  packages/app/src/hooks/useCustomizationData.ts
  packages/app/src/hooks/useQuickAccess.ts
  packages/app/src/types/types.ts
Labels: approved, lgtm

#1176 fix(gitlab): add a dynamic wrapper to expose the gitlab org provider
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/src/module.ts
Labels: approved, lgtm

#1197 RHIDP-428 Add JUnit test results reporter
  .gitignore
  e2e-tests/.gitignore
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#1218 chore(deps): bump to latest roadiehq/backstage-plugin-argo-cd 2.6.4 and roadiehq-backstage-plugin-argo-cd-backend 3.0.0 (RHIDP-2191)
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  yarn.lock
Labels: approved, lgtm
