Repository redhat-developer/rhdh, pull requests merged in 2024-12, with the labels that each got.

#2034 chore(e2e): fix e2e tests and increase timeouts
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#2022 fix: add mui v5 workaround in wrapper code
  dynamic-plugins/wrappers/backstage-community-plugin-acr/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-quay/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-topology/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-notifications/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-signals/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/src/index.ts
Labels: approved, lgtm

#2024 fix(techdocs): fix ReportIssue style issue when loaded as dynamic plugin
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/ShadowRootStylesProvider.tsx
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/addons.tsx
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/wrapped.tsx
Labels: lgtm

#2044 chore(e2e): fix mui v5 button locator
  e2e-tests/playwright/support/pageObjects/global-obj.ts
Labels: approved, lgtm

#1923 test: enable auth providers for nightly jobs
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/value_files/values_showcase-auth-provider-diff-rhbk.yaml
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/setup-environment.spec.ts
  e2e-tests/playwright/utils/api-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  e2e-tests/playwright/utils/authenticationProviders/github-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/msgraph-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/rh-sso-helper.ts
  e2e-tests/playwright/utils/common.ts
  e2e-tests/playwright/utils/helm.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/kube-client.ts
  e2e-tests/playwright/utils/logger.ts
  e2e-tests/playwright/utils/ui-helper.ts
  test-results/.last-run.json
Labels: approved, lgtm

#2029 fix(techdocs): fix ReportIssue style issue when loaded as dynamic plugin [release-1.4]
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/ShadowRootStylesProvider.tsx
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/addons.tsx
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/wrapped.tsx
Labels: approved, lgtm

#2038 chore(e2e): update nightly test OCP level
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1966 docs: adding general rules to e2e contribution guidelines
  docs/e2e-tests/CONTRIBUTING.MD
Labels: approved, lgtm, ok-to-test

#1963 chore(e2e-tests): enable tech radar plugin tests
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
Labels: approved, lgtm

#2060 chore: update location of @backstage-community/plugin-scaffolder-backend-module-annotator
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  packages/backend/package.json
  packages/backend/src/index.ts
  yarn.lock
Labels: approved, lgtm

#2066 chore(e2e): fix catalog scaffolded test
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
Labels: approved, lgtm

#2032 refactor: modularize OpenShift CI script for better maintainability - new
  .ibm/pipelines/cluster/aks/deployment.sh
  .ibm/pipelines/cluster/gke/deployment.sh
  .ibm/pipelines/jobs/aks.sh
  .ibm/pipelines/jobs/gke.sh
  .ibm/pipelines/jobs/main.sh
  .ibm/pipelines/jobs/ocp-v4-15.sh
  .ibm/pipelines/jobs/ocp-v4-16.sh
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved

#2061 chore: patch useRedisSets config for cache fix
  patches/@backstage+backend-defaults+0.4.1.patch
Labels: approved, lgtm

#2067 chore(e2e): fix e2e tests scaffolded
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
Labels: approved, lgtm

#2068 chore(e2e): fix catalog scaffolded test
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
Labels: approved, lgtm

#2079 chore: update dockerfiles
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2057 chore: [release-1.4] bump @backstage/plugin-scaffolder-node
  .yarn/patches/@backstage-plugin-scaffolder-node-npm-0.5.0.patch
  .yarn/patches/@backstage-plugin-scaffolder-node-npm-0.6.1-a2cc13065e.patch
  package.json
  yarn.lock
Labels: approved, lgtm

#2078 chore: [release-1.4] update location of @backstage-community/plugin-scaffolder-backend-module-annotator
  packages/backend/package.json
  packages/backend/src/index.ts
  yarn.lock
Labels: approved, lgtm

#2082 chore: [release-1.4] expose application and system metrics on same port
  docs/dynamic-plugins/installing-plugins.md
  docs/monitoring-and-logging.md
  packages/backend/package.json
  packages/backend/src/instrumentation.js
  yarn.lock
Labels: approved, lgtm

#2076 chore(deps): update dockerfile image
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2073 chore(e2e): ocp ephemeral env setup for e2e-tests
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/cluster/operators/acm/multiclusterhub.yaml
  .ibm/pipelines/cluster/operators/acm/operator-group.yaml
  .ibm/pipelines/cluster/operators/acm/subscription-acm.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/main.sh
  .ibm/pipelines/jobs/ocp-v4-15.sh
  .ibm/pipelines/jobs/ocp-v4-16.sh
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/ocp-cluster-claim-login.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/github-discovery.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#2064 feat(settings): hide detailed build version information and show them on demand
  packages/app/src/components/UserSettings/GeneralPage.tsx
  packages/app/src/components/UserSettings/InfoCard.test.tsx
  packages/app/src/components/UserSettings/InfoCard.tsx
  packages/app/src/components/UserSettings/SettingsPages.tsx
Labels: approved, lgtm

#2089 chore(e2e): fix e2e tests
  .ibm/pipelines/cluster/aks/az.sh
  .ibm/pipelines/cluster/gke/gcloud.sh
  .ibm/pipelines/jobs/main.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Labels: approved

#2090 chore(deps): [release-1.4] bump express-openapi-validator to fix CVE-…
  yarn.lock
Labels: approved, lgtm

#2087 chore: bump @backstage/plugin-scaffolder-node
  .yarn/patches/@backstage-plugin-scaffolder-node-npm-0.5.0.patch
  .yarn/patches/@backstage-plugin-scaffolder-node-npm-0.6.1-a2cc13065e.patch
  package.json
  yarn.lock
Labels: approved, lgtm

#2094 chore(deps): bump express-openapi-validator to fix CVE-2024-45296
  yarn.lock
Labels: approved, lgtm

#2035 chore(e2e-test): [Test automation] Verify Home Page can be customized
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/dynamic-homepage-and-sidebar-config.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/home-page-customization.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2092 fix: [e2e-tests] Improve Github popup login used in catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#2093 chore(redhat-argocd): update wrapper
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#2105 fix: [e2e-tests] - fix verify TLS configuration with external Postgres DB test case
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
Labels: approved, lgtm

#2095 chore(e2e): re-enable tech radar test with fix
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
Labels: approved, lgtm

#2065 chore(e2e): [release-1.4] enable tech radar tests
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
Labels: approved, lgtm

#2104 fix: fix e2e runtime tests namespace
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
Labels: approved, lgtm

#2088 chore(e2e): automate E2E scenario with use of Operator for installation refactored
  .ibm/images/Dockerfile
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/rhdh-operator/rhdh-start-rbac.yaml
  .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
  .ibm/pipelines/utils.sh
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#2111 chore(e2e): fix tech radar tests for nightly
  .ibm/pipelines/jobs/periodic.sh
Labels: approved, lgtm

#2117 chore(e2): rhidp-5296 e2e - main nightly job failing on runtime configuration change step
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#2098 [release-1.4] chore(ci): enable homepage plugin on ci setup
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
Labels: approved, lgtm

#2074 chore(ci): fix k8s jobs, better shebang
  .ibm/pipelines/cluster/aks/az.sh
  .ibm/pipelines/cluster/aks/deployment.sh
  .ibm/pipelines/cluster/gke/deployment.sh
  .ibm/pipelines/cluster/gke/gcloud.sh
  .ibm/pipelines/cluster/osd-gcp/create-osd.sh
  .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
  .ibm/pipelines/jobs/aks.sh
  .ibm/pipelines/jobs/gke.sh
  .ibm/pipelines/jobs/main.sh
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
Labels: approved, lgtm

#2113 fix(wrappers): embed runtime dependencies
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2116 [release-1.3] fix gitlab-org wrapper
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
Labels: approved, lgtm

#1959 docs: adding ci.md documentation 2
  .ibm/pipelines/openshift-ci-tests.sh
  docs/e2e-tests/CI.md
  docs/images/github_diagram.svg
  docs/images/nightly_diagram.svg
Labels: approved

#2121 chore(e2e): rhidp-5301 Plugins Sanity Checks
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/value_files/sanity-check-plugins.yaml
Labels: approved

#2124 fix(rbac): fix overview page styling issues
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  plugins/licensed-users-info-backend/package.json
  yarn.lock
Labels: approved, lgtm

#2132 chore(ci): re-enable `droute`
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2045 test(e2e): fixin rbac tests
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
  e2e-tests/playwright/support/api/rbac-api-structures.ts
  e2e-tests/playwright/support/api/rbac-api.ts
  e2e-tests/playwright/support/api/rhdh-auth-api-hack.ts
  e2e-tests/playwright/support/api/rhdh-auth-hack.ts
  e2e-tests/playwright/support/pages/rbac.ts
Labels: approved, lgtm, ok-to-test

#2136 chore(e2e): skip "Change app-config" e2e test case.
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
Labels: approved, lgtm

#2110 chore(ci): revert nightly job namespace names
  .ibm/pipelines/jobs/periodic.sh
Labels: approved, lgtm
