Repository redhat-developer/rhdh, pull requests merged in 2024-08, with the labels that each got.

#1468 Enable dangerouslyAllowSignInWithoutUserInCatalog option for GitHub
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1464 RHIDP-816 [Test automation] Configure and verify GitLab integration with Discovery
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/gitlab/gitlab-discovery.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/tekton/tekton.ts
Labels: approved, lgtm

#1462 chore(deps): fix CVE-2024-41818
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1451 chore(rbac): update rbac plugin versions
  dynamic-plugins/imports/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1271 updated yarn start in root package.json
  app-config.example.yaml
  package.json
Labels: approved, ok-to-test

#1429 provide kubernetesAuthApi in frontend kubernetes dynamic plugin
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/src/index.ts
  showcase-docs/getting-started.md
Labels: approved

#1331 chore: add steps on how to test proxy on OCP
  docs/proxy.md
Labels: approved

#1475 chore: fix prometheus metrics
  yarn.lock
Labels: approved, lgtm

#1476 RHIDP-3437 Include VMs in the topology view
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/support/pages/Catalog.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/tekton/tekton.ts
Labels: approved, lgtm

#1478 chore: update @parfuemerie-douglas/scaffolder-backend-module-azure-re…
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/dist-dynamic/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  yarn.lock
Labels: approved, lgtm

#1493 Skip Quay.io plugin tests
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
Labels: approved, lgtm

#1485 Fix app-config.yaml
  app-config.yaml
  package.json
  showcase-docs/getting-started.md
Labels: approved, lgtm

#1497 chore: fix CVE-2024-39338
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1487 chore(deps): [1.2.x] update dependency urllib3 to v2.2.2 [security]
  .rhdh/docker/requirements-build.in
  .rhdh/docker/requirements-build.txt
  .rhdh/docker/requirements.in
  .rhdh/docker/requirements.txt
Labels: approved, lgtm

#1500 chore: regen yarn.lock to remove name property
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
Labels: approved, lgtm

#1499 chore: [1.2.x] fix CVE-2024-39338
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1504 chore: update elliptic - CVE-2024-42461
  yarn.lock
Labels: lgtm

#1508 fix(dynamic-plugins-info): improve plugins error message
  plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
Labels: approved, lgtm

#1479 add install method of plugin from container registry
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docker/install-dynamic-plugins.py
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#1514 chore: add a wrapper for the 3scale-backend plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/src/index.ts
  yarn.lock
Labels: approved

#1523 Fixing e2e tests
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved

#1521 Login user with userId for MsGraph authentication
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved

#1512 feat: add dynamic wrapper for ldap plugin
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/yarn.lock
  yarn.lock
Labels: approved, ok-to-test

#1488 [Test Automation] Verify RBAC plugin - REST API
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: lgtm

#1480 [e2e] : RHIDP-3069 - Automate Redis cache scenario
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/redis-cache/redis-deployment.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/package.json
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
  e2e-tests/yarn.lock
Labels: approved, lgtm

#1517 chore(default dynamic plugins): disable all TP plugins by default
  dynamic-plugins.default.yaml
Labels: needs-rebase, approved

#1533 chore(rbac): update rbac plugin versions
  dynamic-plugins/imports/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: lgtm

#1534 [e2e] Fix: Enable default required plugins for scaffoldedfromlink test
  .ibm/pipelines/value_files/values_showcase.yaml
Labels: approved, lgtm

#1520 feat(licensed-users): introduce licensed user info plugin
  .dockerignore
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  packages/backend/package.json
  packages/backend/src/index.ts
  plugins/licensed-users-info-backend/.eslintrc.js
  plugins/licensed-users-info-backend/README.md
  plugins/licensed-users-info-backend/dev/index.ts
  plugins/licensed-users-info-backend/package.json
  plugins/licensed-users-info-backend/src/database/databaseUserInfoStore.ts
  plugins/licensed-users-info-backend/src/index.ts
  plugins/licensed-users-info-backend/src/plugin.ts
  plugins/licensed-users-info-backend/src/service/catalogStore.ts
  plugins/licensed-users-info-backend/src/service/readBackstageTokenExpiration.ts
  plugins/licensed-users-info-backend/src/service/router.test.ts
  plugins/licensed-users-info-backend/src/service/router.ts
  plugins/licensed-users-info-backend/src/setupTests.ts
  yarn.lock
Labels: approved

#1543 chore: add some more owners
  OWNERS
Labels: approved, lgtm

#1518 chore(wrappers): add wrapper for plugin-redhat-argocd and plugin-redhat-argocd-common (RHIDP 3548)
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/src/index.ts
  yarn.lock
Labels: approved

#1541 add bulk import plugin
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/imports/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1542 [e2e]: Save Logs for All Deployed Pods for each PR execution
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#1544 add patches for msgraph to ingest users with no email
  patches/@backstage+plugin-auth-backend+0.22.9.patch
  patches/@backstage+plugin-auth-backend-module-microsoft-provider+0.1.17.patch
  patches/@backstage+plugin-catalog-backend-module-msgraph+0.5.30.patch
Labels: approved, lgtm

#1546 chore: correct string configuration fix
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
Labels: approved, lgtm
