Repository redhat-developer/rhdh, pull requests merged in 2024-03, with the labels that each got.

#1057 chore(admin): enable dynamic-plugins-info
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#1061 Skip Google sign-in e2e test in beforeAll hook
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Labels: approved, lgtm

#1062 Skip Google sign-in e2e test in beforeAll hook
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Labels: lgtm

#1064 Disable Google signin happy path test
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
Labels: approved, lgtm

#1021 [e2e-tests] Add security scan check to quay plugin suite
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#1068 E2E: upload Playwright report and add view report link to PR
  .ibm/pipelines/functions.sh
Labels: approved, lgtm

#1071 Support `resolvePackagePath` for dynamic backend plugins.
  packages/backend/src/index.ts
  packages/backend/src/loader/CommonJSModuleLoader.ts
  packages/backend/src/loader/index.ts
Labels: approved, lgtm

#1080 plugin-scalprum-backend: replace mock-fs with @backstage/backend-test…
  plugins/scalprum-backend/package.json
  plugins/scalprum-backend/src/service/router.test.ts
Labels: approved, lgtm

#1079 feat(ocm): update the ocm backend plugin
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1025 add list of tests in the test log
  .ibm/pipelines/openshift-tests.sh
  e2e-tests/package.json
Labels: lgtm

#1081 update icons on the nav sidebar to make them outlined
  packages/app/src/components/Root/Root.tsx
Labels: approved, lgtm

#1077 fix(scipts): update prettierignore
  .prettierignore
  scripts/update-backstage.mjs
Labels: approved, lgtm

#1094 chore(deps): regen lockfiles to fix cves
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1072 feat(OIDC): adds a forked version of the OIDC auth plugin
  .dockerignore
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  packages/backend/package.json
  packages/backend/src/modules/authProvidersModule.ts
  plugins/auth-backend-module-oidc-provider/.eslintrc.js
  plugins/auth-backend-module-oidc-provider/README.md
  plugins/auth-backend-module-oidc-provider/config.d.ts
  plugins/auth-backend-module-oidc-provider/dev/index.ts
  plugins/auth-backend-module-oidc-provider/package.json
  plugins/auth-backend-module-oidc-provider/src/authenticator.test.ts
  plugins/auth-backend-module-oidc-provider/src/authenticator.ts
  plugins/auth-backend-module-oidc-provider/src/index.ts
  plugins/auth-backend-module-oidc-provider/src/module.test.ts
  plugins/auth-backend-module-oidc-provider/src/module.ts
  plugins/auth-backend-module-oidc-provider/src/resolvers.ts
  showcase-docs/auth.md
  showcase-docs/getting-started.md
  yarn.lock
Labels: approved, lgtm

#1095 fix: downgrade ArgoCD frontend plugin
  .github/renovate.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  yarn.lock
Labels: approved, lgtm

#1098 chore(deps): fix package resolutions
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  yarn.lock
Labels: approved

#1116 chore(deps): bump tekton plugin to 3.5.12
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1118 chore(deps): bump topology plugin to 1.18.8
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1140 chore(deps): update lockfiles
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
Labels: lgtm
