Repository redhat-developer/rhdh, pull requests merged in 2024-10, with the labels that each got.

#1711 chore: rename acr plugin directory references
  app-config.dynamic-plugins.yaml
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1712 chore: rename 3scale plugin paths to reflect the one in community-plugins
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1714 chore(deps): bump @backstage/plugin-techdocs-backend to 1.10.13
  package.json
  yarn.lock
Labels: approved, lgtm

#1715 chore(deps): [release-1.3] bump @backstage/plugin-techdocs-backend t0 1.10.13
  package.json
  yarn.lock
Labels: approved, lgtm

#1718 chore(deps): bump dset to 3.1.4
  package.json
  yarn.lock
Labels: approved, lgtm

#1668 RHIDP-4133: fix(homepage): fix some sonarcloud issues
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
  plugins/dynamic-home-page/app-config.janus-idp.yaml
  plugins/dynamic-home-page/src/hooks/useHomePageMountPoints.ts
  plugins/dynamic-home-page/src/plugin.ts
Labels: approved, lgtm

#1690 RHIDP-4158: fix(ui): hide menu items with no title in sidebar nav
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Labels: approved, lgtm

#1703 fix(ui): fixed console warning
  packages/app/src/components/Root/Root.tsx
Labels: approved, lgtm

#1651 clarify indentation level of config in auth documentation
  docs/auth.md
Labels: approved, lgtm

#1702 docs(dynamic-plugins) update upstream (showcase) documentation about dynamic plugins after the changes to the CLI
  docs/dynamic-plugins.md
Labels: approved, lgtm

#1722 add documentation to set up OIDC auth with Ping Identity
  docs/images/allowed_scopes_ping_identity_app.png
  docs/images/response_and_grant_type_ping_identity_app.png
  docs/ping-identity-env-setup.md
  docs/ping-identity-oidc-setup.md
Labels: approved, lgtm

#1731 Update KEYCLOAK_BASE_URL secret handling
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
Labels: approved, lgtm

#1746 Manual cherry-pick of #1731 and #1741
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#1747 Manual cherry-pick of #1731 and #1741
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#1674 RHIDP-4201: docs(homepage): add techdocs
  plugins/dynamic-home-page/catalog-info.yaml
  plugins/dynamic-home-page/docs/catalog-starred.md
  plugins/dynamic-home-page/docs/catalog-starred.png
  plugins/dynamic-home-page/docs/create-a-new-card.md
  plugins/dynamic-home-page/docs/customization.md
  plugins/dynamic-home-page/docs/default-homepage.png
  plugins/dynamic-home-page/docs/default-size.png
  plugins/dynamic-home-page/docs/featured-docs.md
  plugins/dynamic-home-page/docs/featured-docs.png
  plugins/dynamic-home-page/docs/headline.md
  plugins/dynamic-home-page/docs/headline.png
  plugins/dynamic-home-page/docs/index.md
  plugins/dynamic-home-page/docs/jokes.md
  plugins/dynamic-home-page/docs/jokes.png
  plugins/dynamic-home-page/docs/layout-columns.png
  plugins/dynamic-home-page/docs/layout-example-1-placeholder.png
  plugins/dynamic-home-page/docs/layout-example-2-placeholder.png
  plugins/dynamic-home-page/docs/layout-example-3-placeholder.png
  plugins/dynamic-home-page/docs/layout-options.md
  plugins/dynamic-home-page/docs/markdown.md
  plugins/dynamic-home-page/docs/markdown.png
  plugins/dynamic-home-page/docs/placeholder.md
  plugins/dynamic-home-page/docs/placeholder.png
  plugins/dynamic-home-page/docs/quick-access.md
  plugins/dynamic-home-page/docs/quick-access.png
  plugins/dynamic-home-page/docs/recently-visited.md
  plugins/dynamic-home-page/docs/recently-visited.png
  plugins/dynamic-home-page/docs/search.md
  plugins/dynamic-home-page/docs/search.png
  plugins/dynamic-home-page/docs/top-visited.md
  plugins/dynamic-home-page/docs/top-visited.png
  plugins/dynamic-home-page/mkdocs.yaml
Labels: approved, lgtm

#1728 chore(deps): CVE-2024-37890 force ws resolution to 8.17.1 under backs…
  package.json
  yarn.lock
Labels: approved

#1721 [e2e] RHIDP-4264 - 1st PR: Cleanup and organization
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac-scaffold.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/api/github.ts
  e2e-tests/playwright/support/api/rhdh-auth-hack.ts
  e2e-tests/playwright/support/pages/rbac.ts
Labels: approved, lgtm, ok-to-test

#1734 chore(deps): update rhdh-theme to 0.4.0
  packages/app/package.json
  plugins/dynamic-home-page/package.json
  yarn.lock
Labels: approved, lgtm

#1751 chore(e2e): fix rbac test and remove test-app deployment
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/deployment/deployment-test-app-component.yaml
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1726 fix broken links in TechDocs
  docs/customization.md
  docs/dynamic-plugins.md
  docs/images/example-support-button.png
  docs/images/support-not-configured.png
  docs/proxy.md
Labels: approved, lgtm

#1754 chore(deps): update ocm-backend
  dynamic-plugins/imports/package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1643 e2e: add scenarios to standardize auth providers tests
  .ibm/pipelines/value_files/values-showcase_auth-providers.yaml
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/clear-environment.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/setup-environment.spec.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/Logger.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  e2e-tests/playwright/utils/authenticationProviders/githubHelper.ts
  e2e-tests/playwright/utils/authenticationProviders/msgraphHelper.ts
  e2e-tests/playwright/utils/authenticationProviders/rhssoHelper.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/k8sHelper.ts
  e2e-tests/yarn.lock
Labels: approved

#1758 chore(deps): undo bump @backstage/plugin-techdocs-backend to 1.10.13
  package.json
  yarn.lock
Labels: approved, lgtm

#1759 chore(deps): update elliptic to fix CVE-2024-48949
  yarn.lock
Labels: approved, lgtm

#1486 chore: add RHDH scripts and add them as techdocs
  .gitignore
  docs/keycloak-quickstart.md
  docs/patch-package.md
  docs/rhdh-quickstart-script.md
  patches/README.md
  scripts/keycloak-setup/auth/database-secrets.yaml
  scripts/keycloak-setup/database/postgres.yaml
  scripts/keycloak-setup/deploy-keycloak.sh
  scripts/keycloak-setup/keycloak.yaml
  scripts/patch-package.sh
  scripts/rhdh-openshift-setup/auth/rhdh-secrets.yaml
  scripts/rhdh-openshift-setup/auth/service-account-rhdh-secret.yaml
  scripts/rhdh-openshift-setup/quick-start-rhdh.sh
  scripts/rhdh-openshift-setup/resources/cluster-roles/cluster-role-binding-k8s.yaml
  scripts/rhdh-openshift-setup/resources/cluster-roles/cluster-role-binding-ocm.yaml
  scripts/rhdh-openshift-setup/resources/cluster-roles/cluster-role-k8s.yaml
  scripts/rhdh-openshift-setup/resources/cluster-roles/cluster-role-ocm.yaml
  scripts/rhdh-openshift-setup/resources/daemon-sets/daemon-set.yaml
  scripts/rhdh-openshift-setup/resources/deployments/backstage-test.yaml
  scripts/rhdh-openshift-setup/resources/jobs/cron-job.yaml
  scripts/rhdh-openshift-setup/resources/jobs/pi-job.yaml
  scripts/rhdh-openshift-setup/resources/pipelines/hello-world-pipeline-run.yaml
  scripts/rhdh-openshift-setup/resources/pipelines/hello-world-pipeline.yaml
  scripts/rhdh-openshift-setup/resources/rbac-policies.yaml
  scripts/rhdh-openshift-setup/resources/rhdh-configmap.yaml
  scripts/rhdh-openshift-setup/resources/service-account-rhdh.yaml
  scripts/rhdh-openshift-setup/resources/stateful-sets/stateful-set.yaml
  scripts/rhdh-openshift-setup/values.yaml
Labels: approved, lgtm

#1763 chore(e2e): fix aks tests
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#1737 chore: drop support for node18 as of 1.4...
  package.json
Labels: approved, lgtm

#1762 chore(deps): CVE-2024-37890 force ws resolution to 8.17.1 [1.3]
  package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1771 [e2e] reduce test timeout
  e2e-tests/playwright.config.ts
Labels: approved, lgtm, ok-to-test

#1736 chore: [release-1.3] update 3scale references in dynamic-plugins-info
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
Labels: approved, lgtm

#1753 chore(npm registry default): set default npm registry to https://registry.npmjs.org/ instead of cachito; also set path to cafile (RHIDP-4410)
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#1783 fix(app): proxy for tech-radar
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/api/CustomTechRadar.ts
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/index.ts
Labels: approved, lgtm

#1778 RHIDP-4544: fix(ui): hide menu items with no title in sidebar nav (#1690)
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Labels: approved, lgtm

#1782 chore(deps): remove dset version 3.1.4 from resolutions
  package.json
  yarn.lock
Labels: approved, lgtm

#1732 [e2e] ReportPortal enhancements
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm, ok-to-test

#1801 chore: update my github username (owners file)
  OWNERS
Labels: approved, lgtm

#1806 [1.3] Clean up SercvieAccount list for OCM test
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
Labels: approved, lgtm

#1788 chore(deps): release-1.3, update body-parser, mysql2 and braces
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved

#1805 add missing ServiceAccount for ClusterRoleBinding
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
Labels: approved, lgtm

#1812 chore: update owners list for e2e tests
  .ibm/OWNERS
  OWNERS
  e2e-tests/OWNERS
Labels: approved, lgtm

#1738 chore: add dynamic wrapper for nexus-repository-manager plugin
  README.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.tsx
  yarn.lock
Labels: approved

#1832 chore: add workflow to automate backstage updates
  .github/workflows/update-backstage.yaml
  .github/workflows/versioned-build-image.yaml
  scripts/update-backstage.mjs
Labels: approved, lgtm

#1833 fix: add --no-immutable flag in update-backstage script
  .github/workflows/update-backstage.yaml
  scripts/update-backstage.mjs
Labels: approved, lgtm

#1847 fix(ui): added null check to fix runtime error
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
Labels: approved, lgtm

#1836 fix(e2e): disable tekton plugins and tekton tests
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts
Labels: approved

#1854 fix(wrappers): export * instead of default from frontend plugins
  dynamic-plugins/wrappers/backstage-community-plugin-acr/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-github-actions/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-github-issues/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-jenkins/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-techdocs/src/index.ts
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-jfrog-artifactory/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-quay/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-rbac/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-tekton/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-topology/src/index.ts
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/src/index.ts
Labels: approved, lgtm

#1861 chore(e2e): enhance namespace deletion handling
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved

#1789 chore(docs): version matrix for dynamic plugins
  docs/dynamic-plugins/dynamic-plugins.md
  docs/dynamic-plugins/versions.md
Labels: approved, lgtm
