Repository redhat-developer/rhdh, pull requests merged in 2024-11, with the labels that each got.

#1870 fix: patch oidc to include preferredUsernameMatchingUserEntityName
  .yarn/patches/@backstage-plugin-auth-backend-module-oidc-provider-npm-0.3.1-6fab98121c.patch
  package.json
  yarn.lock
Labels: approved, lgtm

#1873 chore(e2e): use a fixed digit of SHORT_SHA for image name
  .github/workflows/next-build-image.yaml
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#1860 chore(docs): add a section to the dynamic-plugins.md that discusses how to debug dynamic plugins
  docs/dynamic-plugins/dynamic-plugins.md
Labels: approved, lgtm

#1874 chore: add wrapper tests
  .github/workflows/pr.yaml
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/_utils/package.json
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  package.json
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.test.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  scripts/rhdh-openshift-setup/values.yaml
  scripts/update-backstage.mjs
  turbo.json
  yarn.lock
Labels: approved, lgtm

#1859 chore: update tech-radar to 1.0
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/src/api/CustomTechRadar.ts
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/src/data/data-default.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/src/index.ts
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#1877 chore(fix): update petstore url to fix tests
  catalog-entities/apis/petstore.yaml
Labels: lgtm

#1852 chore(docs): fill in some missing documentation
  docs/dynamic-plugins/dynamic-plugins.md
Labels: approved, lgtm

#1871 chore(metadata): fix support states
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-quay/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-rbac/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-tekton/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-topology/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-quay-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-quay-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-regex-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-regex-dynamic/package.json
Labels: approved

#1882 test(e2e): deleting pointless assertion for "Verify all 12 Software Templates appear in the Create page" test
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
Labels: approved, lgtm

#1823 chore(release): update keycloak-backend for RHDH 1.3.1
  dynamic-plugins/imports/package.json
Labels: approved

#1814 [release-1.3] fix: update janus-idp/cli in wrappers to 1.13.3
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd-common/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-logs/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  packages/app/package.json
  yarn.lock
Labels: approved

#1884 chore(deps): release-1.3 update peer deps
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1842 chore(deps): fix CVE-2024-21536
  yarn.lock
Labels: approved, lgtm

#1835 fix(deps): upgrade argocd plugin to fix a CVE [release-1.3]
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  yarn.lock
Labels: approved, lgtm

#1822 chore(release): update rbac-backend
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1891 chore(deps): dedupe @types/http-proxy
  yarn.lock
Labels: approved, lgtm

#1869 chore(e2e): fix e2e tests
  .ibm/images/Dockerfile
  .ibm/pipelines/resources/config_map/configmap-rbac-policy-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/src/bundle.ts
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/src/dynamic/index.ts
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/src/index.ts
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/src/index.ts
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/e2e/github-discovery.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-enabled.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
  packages/backend/package.json
  scripts/rhdh-openshift-setup/values.yaml
  yarn.lock
Labels: approved, lgtm

#1875 chore: add wrapper for keycloak
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  README.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/turbo.json
  e2e-tests/playwright/support/testData/dynamic-plugins-info.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved

#1898 chore: add wrapper for scaffolder-backend-module-sonarqube
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-scaffolder-backend-module-sonarqube-dynamic/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-sonarqube-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-sonarqube-dynamic/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#1865 chore(dynamic-plugins): update dynamic wrapper for migrated jfrog-art…
  README.md
  app-config.dynamic-plugins.yaml
  docs/index.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-jfrog-artifactory/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-jfrog-artifactory/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved

#1899 chore: fix export-dynamic:clean in tech-radar-backend
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/package.json
Labels: approved, lgtm, do-not-merge/hold

#1826 chore(ci): update GH workflow names
  .github/workflows/cache-cleanup.yaml
  .github/workflows/on-new-issue.yaml
  .github/workflows/pr-build-image.yaml
  .github/workflows/pr-semantic.yaml
Labels: approved, lgtm

#1890 chore: create wrappers for ocm plugins
  .ibm/pipelines/README.md
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  README.md
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-ocm/turbo.json
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/support/testData/dynamic-plugins-info.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  scripts/rhdh-openshift-setup/values.yaml
  yarn.lock
Labels: approved

#1902 chore: update wrappers for bulk import plugins
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-bulk-import/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  scripts/rhdh-openshift-setup/values.yaml
  yarn.lock
Labels: approved, lgtm

#1901 fix(docker): unable to build image using podman
  .github/workflows/pr.yaml
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  package.json
  scripts/update-Dockerfile.sh
Labels: approved, lgtm

#1913 chore(docker): ensure yarn is on the path (RHIDP-4211)
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#1827 feat(e2e): implemented test to check download users link
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#1903 fix(corporate-proxy): use the built-in `EnvHttpProxyAgent` from `undici` to fix the proxy issues reported
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docs/corporate-proxy.md
  docs/proxy.md
  packages/backend/src/corporate-proxy.ts
Labels: approved, lgtm

#1828 chore(deps): update dynamic home page from mui v4 to v5
  plugins/dynamic-home-page/docs/headline.md
  plugins/dynamic-home-page/package.json
  plugins/dynamic-home-page/src/components/Markdown.tsx
  plugins/dynamic-home-page/src/components/Placeholder.tsx
  plugins/dynamic-home-page/src/components/QuickAccessCard.tsx
  plugins/dynamic-home-page/src/components/ReadOnlyGrid.tsx
  plugins/dynamic-home-page/src/components/SearchBar.tsx
  yarn.lock
Labels: approved, lgtm

#1927 chore(keycloak): update export-dynamic command
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
Labels: approved, lgtm

#1867 fix(e2e): [1.2.x] disable tekton
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved

#1798 test: verify TLS config with Postgres in Amazon RDS using Helm
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/postgres-db/dynamic-plugins-root-PVC.yaml
  .ibm/pipelines/resources/postgres-db/postgres-cred.yaml
  .ibm/pipelines/resources/postgres-db/postgres-crt-rds.yaml
  .ibm/pipelines/resources/postgres-db/values-showcase-postgres.yaml
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
  e2e-tests/playwright/utils/k8sHelper.ts
Labels: approved

#1735 chore(deps): [1.2.x] Bump Express to v4.21.0 to fix a number of CVEs
  dynamic-plugins/imports/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/dist-dynamic/yarn.lock
  package.json
  packages/backend/package.json
  plugins/auth-backend-module-oidc-provider/package.json
  plugins/dynamic-plugins-info-backend/package.json
  plugins/scalprum-backend/package.json
  yarn.lock
Labels: approved

#1936 test(e2e): hotfix for reauth github problem
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1937 fix: hide commands related to tokens
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1895 chore(docs): installing external plugins and dynamic-plugins doc cleanup
  docs/dynamic-plugins/debugging.md
  docs/dynamic-plugins/dynamic-plugins.md
  docs/dynamic-plugins/export-derived-package.md
  docs/dynamic-plugins/frontend-plugin-wiring.md
  docs/dynamic-plugins/installing-plugins.md
  docs/dynamic-plugins/local.md
  docs/dynamic-plugins/packaging-dynamic-plugins.md
  docs/dynamic-plugins/wrapping-plugins.md
Labels: approved, lgtm

#1934 chore(deps): bump up peer deps and more CVEs
  dynamic-plugins/imports/package.json
  yarn.lock
Labels: approved, lgtm

#1935 fix(e2e): fix Verify TLS config with Postgres in Amazon RDS using Helm
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
Labels: approved, lgtm

#1803 chore(e2e): rhdh deployment on openshift dedicated (osd) on gcp using helm chart
  .ibm/images/Dockerfile
  .ibm/pipelines/cluster/osd-gcp/README.md
  .ibm/pipelines/cluster/osd-gcp/create-osd.sh
  .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm, ok-to-test

#1729 fix: fix GitLab auth by resolving via username not userId
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#1777 chore(wrapper): add notifications plugin wrappers
  .rhdh/docker/Dockerfile
  README.md
  app-config.dynamic-plugins.yaml
  docker/Dockerfile
  docs/index.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-plugin-notifications/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-notifications/tsconfig.json
  dynamic-plugins/wrappers/backstage-plugin-notifications/turbo.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-plugin-signals/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals/src/index.ts
  dynamic-plugins/wrappers/backstage-plugin-signals/tsconfig.json
  dynamic-plugins/wrappers/backstage-plugin-signals/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#1761 feat(app): introduce flavor configuration value
  app-config.yaml
  docs/customization.md
  packages/app/config.d.ts
Labels: approved, lgtm

#1779 chore: add link checker workflow
  .github/workflows/link-checker.config.json
  .github/workflows/link-checker.yaml
  CONTRIBUTING.md
  README.md
  docs/audit-log.md
  docs/customization.md
  docs/dynamic-plugins/export-derived-package.md
  docs/dynamic-plugins/frontend-plugin-wiring.md
  docs/dynamic-plugins/installing-plugins.md
  docs/dynamic-plugins/packaging-dynamic-plugins.md
  docs/dynamic-plugins/wrapping-plugins.md
  docs/e2e-tests/README.md
  docs/index.md
  docs/mkdocs.yml
  docs/monitoring-and-logging.md
  e2e-tests/README.md
Labels: approved, lgtm

#1940 chore: update quay-actions wrapper
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-quay-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-quay-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-scaffolder-backend-module-quay-dynamic/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/package.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#1946 chore(deps): fix CVE-2024-21538
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1945 chore: update analytics-provider-segment wrapper
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .rhdh/docker/Dockerfile
  app-config.dynamic-plugins.yaml
  docker/Dockerfile
  docs/index.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/turbo.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-analytics-provider-segment/turbo.json
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-enabled.spec.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#1724 fix(homepage): fix todos and add support for top and recently visited cards
  packages/app/src/components/AppBase/AppBase.tsx
  plugins/dynamic-home-page/dev/index.tsx
  plugins/dynamic-home-page/package.json
  plugins/dynamic-home-page/src/components/DynamicHomePage.tsx
  plugins/dynamic-home-page/src/components/FeaturedDocsCard.tsx
  plugins/dynamic-home-page/src/components/QuickAccessCard.tsx
  plugins/dynamic-home-page/src/components/VisitListener.tsx
  plugins/dynamic-home-page/src/plugin.ts
  yarn.lock
Labels: approved, lgtm

#1942 chore: export tech radar icon from wrapper
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/src/index.ts
Labels: approved, lgtm

#1881 feat(backend): add service factories by default
  docs/dynamic-plugins/override-core-services.md
  packages/backend/package.json
  packages/backend/src/defaultServiceFactories.test.ts
  packages/backend/src/defaultServiceFactories.ts
  packages/backend/src/index.ts
  packages/backend/src/logger/customLogger.ts
  yarn.lock
Labels: approved, lgtm

#1790 chore(e2e): automate custom theme dynamic plugin
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/data/theme-constants.ts
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
Labels: approved, lgtm

#1961 fix(pagerduty): update to remove no embed as dependencies
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
Labels: approved, lgtm

#1962 chore(docs): dynamic plugins index
  docs/customization.md
  docs/dynamic-plugins/dynamic-plugins.md
  docs/dynamic-plugins/index.md
Labels: approved, lgtm

#1960 chore(deps): update roadie scaffolder modules
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/src/index.ts
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/src/index.ts
  yarn.lock
Labels: approved, lgtm

#1973 chore(e2e): reenable scaffolder-backend-module-http-request test
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1958 chore(e2e): add INT & ERR trap for e2e-tests job cleanup.
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#1974 docs: fix grammar and style issues
  docs/dynamic-plugins/debugging.md
  docs/dynamic-plugins/export-derived-package.md
  docs/dynamic-plugins/frontend-plugin-wiring.md
  docs/dynamic-plugins/installing-plugins.md
  docs/dynamic-plugins/local.md
  docs/dynamic-plugins/override-core-services.md
  docs/dynamic-plugins/packaging-dynamic-plugins.md
  e2e-tests/README.md
Labels: approved, lgtm

#1975 chore(owners): add more approvers
  OWNERS
Labels: approved, lgtm

#1964 chore(deps): 1.4 fix CVE-2024-21534
  yarn.lock
Labels: approved, lgtm

#1924 chore(e2e): optimize .ibm Dockerfile for Improved Build Performance and Dependency Updates
  .ibm/images/Dockerfile
Labels: approved, lgtm

#1953 chore(e2e): rhidp-4958 re-enable the flaky test - catalog-entity refresh is denied after DELETE
  e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
  e2e-tests/playwright/support/pages/rbac.ts
Labels: approved, lgtm

#1977 fix(deps): update dependencies (non-major)
  packages/app/package.json
  plugins/dynamic-home-page/package.json
  plugins/dynamic-plugins-info/package.json
  plugins/licensed-users-info-backend/package.json
  yarn.lock
Labels: approved, lgtm

#1978 chore(docs): add dynamic plugins examples doc
  docs/dynamic-plugins/examples.md
  docs/dynamic-plugins/index.md
Labels: approved, lgtm

#1983 chore(ci): playwright install only chromium
  .ibm/pipelines/openshift-ci-tests.sh
  docs/e2e-tests/README.md
Labels: approved, lgtm

#1850 chore(e2e): rhidp-4049 change app-config at e2e test runtime
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/k8sHelper.ts
  yarn.lock
Labels: approved, lgtm

#1994 fix(rbac): update rbac-backend plugin
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1954 docs: update OpenTelemetry set up documentation
  docs/monitoring-and-logging.md
Labels: approved, lgtm

#2003 fix(e2e): disable broken/flaky tests and add support for MUI v5 buttons in playwright tests
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac-api.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
Labels: approved, lgtm

#1950 test(e2e): revert a hotfix from autumn 2024
  e2e-tests/playwright/e2e/github-discovery.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-with-external-postgres-db.spec.ts
Labels: approved, lgtm

#2006 fix(dynamic plugins): log plugin load errors
  packages/app/src/utils/dynamicUI/initializeRemotePlugins.ts
Labels: approved, lgtm

#1968 feat(rbac): update rbac plugin to 1.33.2
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  yarn.lock
Labels: approved, lgtm

#1909 test(e2e): cut on some timeouts
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#1984 chore(deps): update bulk import plugins
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  yarn.lock
Labels: approved, lgtm

#2012 chore(ci): re-enable `droute` and don't fail on pull requests
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#1695 chore(e2e-test): [Test automation] Verify Topology is a supported plugin and E2E scenario
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#1969 fix(homepage): wrapper update (incl update @scalprum/react-core from 0.8 to 0.9)
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  yarn.lock
Labels: approved, lgtm

#2013 chore(e2e): configure and enable PR check and nightly e2e job for branch release-1.4
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  e2e-tests/package.json
Labels: approved, lgtm
