Repository redhat-developer/rhdh, pull requests merged in 2024-07, with the labels that each got.

#1320 [Test automation] OpenShift Learning Path. The link from the learning path should open a new tab
  e2e-tests/.gitignore
  e2e-tests/playwright/e2e/learning-path-page.spec.ts
  e2e-tests/yarn.lock
Labels: approved, lgtm, ok-to-test

#1370 chore(deps): fix CVE-2024-39008
  yarn.lock
Labels: approved, lgtm

#1373 chore(owners): add new reviewers
  OWNERS
Labels: approved, lgtm

#1368 RHIDP-744 [Test Automation] Automate RHDH theme customization - E2E
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/support/pageObjects/global-obj.ts
  e2e-tests/playwright/utils/APIHelper.ts
  e2e-tests/playwright/utils/UIhelper.ts
  e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
Labels: approved, lgtm

#1390 RHIDP-3159: Disable failing GitHub test
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1383 chore: add catalog-backend patch with endpoint audit logging
  patches/@backstage+plugin-catalog-backend+1.22.0.patch
Labels: approved, lgtm

#1394 chore(deps): bump argocd version to 1.2.3
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1395 fix(argocd): bump the argocd version to include latest bug fixes
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1381 fix(ui): update config at runtime to apply branding
  packages/app/public/index.html
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/Root/ConfigUpdater.tsx
Labels: approved, lgtm

#1398 chore(docker): remove NODE_OPTIONS in favor of embedding it into the ENTRYPOINT
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#1367 Pull in scaffolder-relation-processor plugin from @backstage-community to 1.2.x branch of janus-showcase because it is the new scope.
  dynamic-plugins/imports/package.json
  yarn.lock
Labels: approved

#1396 [Test automation] Configure and verify GitHub integration with Multi-Org data fetching
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
Labels: approved, lgtm

#1386 [e2e] Increase Plawright resolution to 1080p
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1397 chore: add catalog audit logging patches for 1.26.5
  patches/@backstage+plugin-catalog-backend+1.21.1.patch
Labels: approved, lgtm

#1362 [e2e] Link Scaffolded Templates to Catalog Items
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/utils/APIEndpoints.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved

#1415 chore(rbac): update rbac rbac-backend and rbac-common plugins versions
  README.md
  dynamic-plugins/imports/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1404 [1.2.x] RHIDP-3159: Disable failing GitHub test for
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved

#1421 chore(deps): add backstage.pluginId values derived from the plugin folder name (RHIDP-3236)
  dynamic-plugins/wrappers/backstage-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-kubernetes/package.json
  dynamic-plugins/wrappers/backstage-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/parfuemerie-douglas-scaffolder-backend-module-azure-repositories/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
Labels: approved, lgtm

#1417 chore(rbac): update rbac rbac-backend and rbac-common plugins versions
  dynamic-plugins/imports/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved

#1419 chore(deps): update rhdh theme package
  packages/app/config.d.ts
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1428 [e2e] Fix Frequent 2FA Code Reuse Issue in github test case
  e2e-tests/playwright/utils/Common.ts
  e2e-tests/playwright/utils/UIhelper.ts
Labels: approved, lgtm

#1418 chore(deps): update rhdh theme package
  packages/app/config.d.ts
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#1408 chore(deps): bump version of backstage-plugin-catalog-backend-module-gitlab-org-dynamic
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
Labels: approved, lgtm

#1427 RHIDP-3249: fix(learningpath): restore spacing between cards
  packages/app/src/components/learningPaths/LearningPathsPage.tsx
Labels: approved, lgtm

#1406 bump keycloak-backend plugin version
  dynamic-plugins/imports/package.json
Labels: approved, lgtm

#1426 RHIDP-3248: fix(learningpath): restore spacing between cards
  packages/app/src/components/learningPaths/LearningPathsPage.tsx
Labels: approved, lgtm

#1449 chore(nuff): replace link to broken janus slack with backstage discord
  catalog-entities/components/showcase.yaml
Labels: lgtm

#1447 chore(rbac): update rbac plugin versions
  dynamic-plugins/imports/package.json
  packages/app/package.json
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#1448 ensure that images contain only the minimum set of dependencies
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#1456 [e2e] Fix Learning Path test case
  e2e-tests/playwright/e2e/learning-path-page.spec.ts
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm

#1443 feat: add configuration to audit log to a rotating file
  packages/backend/package.json
  packages/backend/src/logger/config.d.ts
  packages/backend/src/logger/customLogger.ts
  showcase-docs/audit-log.md
  yarn.lock
Labels: approved, lgtm

#1438 add dangerouslySignInWithoutUserInCatalog option
  packages/app/config.d.ts
  packages/backend/src/modules/authProvidersModule.ts
  showcase-docs/auth.md
Labels: approved, lgtm

#1457 [e2e] Fix: Increase beforeAll hook timeout
  e2e-tests/playwright/utils/Common.ts
Labels: approved, lgtm
