Repository redhat-developer/rhdh, pull requests merged in 2025-06, with the labels that each got.

#2843 test(e2e): flpath-2284 - Add notfication ui test to RHDH
  e2e-tests/playwright/e2e/plugins/notifications/filterNotificationSeverityCritical.spec.ts
  e2e-tests/playwright/support/api/notifications-api-structures.ts
  e2e-tests/playwright/support/api/notifications.ts
  e2e-tests/playwright/support/pages/Workflows.ts
  e2e-tests/playwright/support/pages/notifications.ts
  e2e-tests/playwright/support/pages/orchestrator.ts
  e2e-tests/playwright/utils/navbar.ts
Labels: approved, lgtm, ok-to-test

#2929 chore(ci): move enhanced reporting to post step
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2862 chore(e2e): rhidp-7172 Plugin 'permission' fails during startup
  .ibm/images/Dockerfile
  .ibm/pipelines/clear-database.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#2757 [release-1.6] chore(e2e): add tests for rbac tests for the kubernetes plugin
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/plugins/kubernetes/kubernetes-rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/page-obj.ts
  e2e-tests/playwright/support/pages/kubernetes.ts
Labels: approved, lgtm

#2938 chore(ci): fix reporting
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2940 chore(ci): enhanced CI reporting cherry-pick
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2944 chore: release-1.6: update tar-fs to fix CVE-2025-48387
  yarn.lock
Labels: approved, lgtm

#2943 chore: update tar-fs to fix CVE-2025-48387
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#2967 docs: remove broken link
  docs/dynamic-plugins/export-derived-package.md
Labels: approved, lgtm

#2978 fix(e2e): add NODE_TLS_REJECT_UNAUTHORIZED env var in operator test config to re-enable topology, Kubernetes-actions, and OCM tests
  .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm

#2979 docs: remove broken link
  docs/dynamic-plugins/export-derived-package.md
Labels: approved, lgtm

#2972 test: refactor auth providers job
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/auth-providers.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-auth-provider-diff-rhbk.yaml
  e2e-tests/.gitignore
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/authProviders/README.md
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/clear-environment.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/github.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft.spec.ts
  e2e-tests/playwright/e2e/authProviders/oidc.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/setup-environment.spec.ts
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/utils/api-helper.ts
  e2e-tests/playwright/utils/authentication-providers/keycloak-helper.ts
  e2e-tests/playwright/utils/authentication-providers/msgraph-helper.ts
  e2e-tests/playwright/utils/authentication-providers/rhdh-deployment.ts
  e2e-tests/playwright/utils/authentication-providers/yamls/backstage.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/configmap.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/dynamic-plugins-config.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/rbac-policy.csv
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  e2e-tests/playwright/utils/authenticationProviders/github-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/msgraph-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/rh-sso-helper.ts
  e2e-tests/playwright/utils/common.ts
  e2e-tests/playwright/utils/constants.ts
  e2e-tests/playwright/utils/helm.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/kube-client.ts
  e2e-tests/playwright/utils/logger.ts
Labels: approved, lgtm

#2982 refactor(kube-client): replace LOGGER with console.log for logging in KubeClient methods
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#2997 test: remove workers limit from auth-providers job
  e2e-tests/package.json
Labels: approved, lgtm

#2980 feat: make UUID claim key in oidcLdapUuidMatchingAnnotation resolver configurable
  packages/backend/src/modules/rhdhSignInResolvers.ts
Labels: approved, lgtm

#2995 refactor(e2e): comment out existing tests and enhance notification handling
  .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
  e2e-tests/playwright/support/api/notifications.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2999 test: refactor auth providers job to use ephemeral clusters
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/auth-providers.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-auth-provider-diff-rhbk.yaml
  e2e-tests/.gitignore
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/authProviders/README.md
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/clear-environment.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/github.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft.spec.ts
  e2e-tests/playwright/e2e/authProviders/oidc.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/setup-environment.spec.ts
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/utils/api-helper.ts
  e2e-tests/playwright/utils/authentication-providers/keycloak-helper.ts
  e2e-tests/playwright/utils/authentication-providers/msgraph-helper.ts
  e2e-tests/playwright/utils/authentication-providers/rhdh-deployment.ts
  e2e-tests/playwright/utils/authentication-providers/yamls/backstage.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/configmap.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/dynamic-plugins-config.yaml
  e2e-tests/playwright/utils/authentication-providers/yamls/rbac-policy.csv
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  e2e-tests/playwright/utils/authenticationProviders/github-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/msgraph-helper.ts
  e2e-tests/playwright/utils/authenticationProviders/rh-sso-helper.ts
  e2e-tests/playwright/utils/common.ts
  e2e-tests/playwright/utils/constants.ts
  e2e-tests/playwright/utils/helm.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/kube-client.ts
  e2e-tests/playwright/utils/logger.ts
Labels: approved, lgtm

#3007 chore(branding): use RHDH branding in app-config files (RHIDP-7883); also fix yaml indents so as to be consistent with downstream after code manipulation, so deltas are smaller
  app-config.dynamic-plugins.yaml
  app-config.example.production.yaml
  app-config.example.yaml
  app-config.production.yaml
  app-config.yaml
Labels: approved

#3029 fix(e2e): update backstage-showcase refs to rhdh
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/e2e/techdocs.spec.ts
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Labels: approved, lgtm

#2977 feat: add config to allow for auxiliary auth providers without identity resolution
  docs/auth.md
  e2e-tests/playwright/e2e/authProviders/github.spec.ts
  e2e-tests/playwright/e2e/authProviders/oidc.spec.ts
  e2e-tests/playwright/utils/common.ts
  packages/backend/src/modules/authProvidersModule.ts
Labels: approved, lgtm

#3001 chore(e2e): topology pipeline test fix
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm

#3006 chore: add default configs for msgraph dynamic plugin
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#2760 [release-1.6] chore(e2e): introduce e2e tests for RBAC Auditor log
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/audit-log/auditor-catalog.spec.ts
  e2e-tests/playwright/e2e/audit-log/auditor-rbac.spec.ts
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
  e2e-tests/playwright/e2e/audit-log/log-utils.ts
  e2e-tests/playwright/e2e/audit-log/logs.ts
  e2e-tests/playwright/e2e/audit-log/rbac-test-utils.ts
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/api/rbac-api.ts
  e2e-tests/playwright/support/pages/catalog-import.ts
  e2e-tests/playwright/utils/api-helper.ts
Labels: approved, lgtm

#3017 fix(extensions): allow service to call /loaded-plugins
  plugins/dynamic-plugins-info-backend/src/service/router.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
Labels: approved, lgtm

#3033 test: move github happy path tests to the main e2e job
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/support/testData/resources.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#3016 chore(config): add orchestrator plugin to dynamic-plugins.default.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
Labels: approved, lgtm

#3049 chore: update @roadiehq/scaffolder-backend-module-http-request
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm
