Repository redhat-developer/rhdh, pull requests merged in 2025-07, with the labels that each got.

#2890 chore(feat): sealight integration with openshifit-ci ocp job
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
  e2e-tests/package.json
  e2e-tests/yarn.lock
Labels: approved, lgtm

#3048 fix(extensions): add contrib techdocs addons plugin
  catalog-entities/marketplace/packages/backstage-plugin-techdocs-module-addons-contrib.yaml
  catalog-entities/marketplace/plugins/all.yaml
  catalog-entities/marketplace/plugins/contrib-techdocs-addons.yaml
Labels: approved, lgtm

#3077 test: add default msgraph envs
  e2e-tests/playwright/e2e/authProviders/microsoft.spec.ts
Labels: approved, lgtm

#3078 chore(e2e): rhidp-8042 Create Azure Policy to Enforce Default Tags for RHDH QE Subscription
  .ibm/pipelines/cluster/aks/auto-label/create-azure-tag-policy.sh
Labels: approved, lgtm

#3026 chore(deps): bump third party plugins to 1.39.1
  catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab-backend.yaml
  catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml
  catalog-entities/marketplace/packages/pagerduty-backstage-plugin-backend.yaml
  catalog-entities/marketplace/packages/pagerduty-backstage-plugin.yaml
  catalog-entities/marketplace/packages/parfuemerie-douglas-scaffolder-backend-module-azure-repositorie.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-argo-cd-backend.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-datadog.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-insights.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-pull-requests.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-jira.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-security-insights.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-argocd.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-utils.yaml
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/package.json
  dynamic-plugins/wrappers/pagerduty-backstage-plugin/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-insights/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-github-pull-requests/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-argocd-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3070 chore(deps): update the catalog entities to match version updates
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-bitbucket-cloud.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-bitbucket-server.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-github-org.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-github.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-gitlab-org.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-gitlab.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-ldap.yaml
  catalog-entities/marketplace/packages/backstage-plugin-catalog-backend-module-msgraph.yaml
  catalog-entities/marketplace/packages/backstage-plugin-kubernetes-backend.yaml
  catalog-entities/marketplace/packages/backstage-plugin-kubernetes.yaml
  catalog-entities/marketplace/packages/backstage-plugin-notifications-backend-module-email.yaml
  catalog-entities/marketplace/packages/backstage-plugin-notifications-backend.yaml
  catalog-entities/marketplace/packages/backstage-plugin-notifications.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-azure.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-bitbucket-cloud.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-bitbucket-server.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-gerrit.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-github.yaml
  catalog-entities/marketplace/packages/backstage-plugin-scaffolder-backend-module-gitlab.yaml
  catalog-entities/marketplace/packages/backstage-plugin-signals-backend.yaml
  catalog-entities/marketplace/packages/backstage-plugin-signals.yaml
  catalog-entities/marketplace/packages/backstage-plugin-techdocs-backend.yaml
  catalog-entities/marketplace/packages/backstage-plugin-techdocs-module-addons-contrib.yaml
  catalog-entities/marketplace/packages/backstage-plugin-techdocs.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-bulk-import-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-bulk-import.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-dynamic-home-page.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-floating-action-b.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-header.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml
Labels: approved, lgtm

#3090 chore: remove rhdh-bot chart references
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#3072 chore: rhidp-8040 Automate IBM Cloud OpenShift Cluster Creation with Tagging Support
  .ibm/pipelines/cluster/ibm/create-openshift-cluster.sh
Labels: approved

#3092 chore: bump keycloak plugin version and test sanitize[User/Group]NameTransformer
  catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-keycloak.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/yarn.lock
  e2e-tests/playwright/e2e/authProviders/oidc.spec.ts
Labels: approved, lgtm

#3043 fix: add missing favicon and change link
  packages/app/public/favicon-192x192.png
  packages/app/public/index.html
Labels: lgtm

#3097 chore: update pbkdf2 to v3.1.3
  yarn.lock
Labels: approved, lgtm

#3105 chore(e2e): skip failing bulk-import and global-header
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Labels: approved, lgtm

#3099 chore(deps): bump adoptions insights backend plugin
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3111 chore: update LDAP plugin support to production
  catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic/package.json
Labels: approved, lgtm

#3113 chore: update parfuemerie-douglas-scaffolder-backend-module-azure-repositories to fix CVE-2024-53983
  dynamic-plugins/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3079 chore: add default configs for ldap dynamic plugin
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#2950 feat: update our `ErrorPage` props to match Backstage props
  packages/app/src/components/ErrorPages/ErrorPage.tsx
  packages/app/src/components/ErrorPages/NotFoundErrorPage.tsx
  packages/app/src/components/ErrorPages/errorButtons/ContactSupportButton.tsx
Labels: approved, lgtm

#3087 chore: add orchestrator deployment to RBAC deployment
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
Labels: approved, lgtm, ok-to-test

#3124 chore(deps): update extensions plugin wrappers
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/yarn.lock
  e2e-tests/playwright/e2e/extensions.spec.ts
Labels: approved, lgtm

#3108 chore(ci): fix Helm k8s deployments
  .ibm/images/Dockerfile
  .ibm/pipelines/cluster/aks/aks-helm-deployment.sh
  .ibm/pipelines/cluster/eks/eks-helm-deployment.sh
  .ibm/pipelines/cluster/gke/gke-helm-deployment.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase-rbac_EKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase-rbac_GKE.yaml
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_EKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
  e2e-tests/playwright/e2e/smoke-test.spec.ts
Labels: approved, lgtm

#3082 chore: update Dockerfile install dynamic plugin script chmod
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#3146 fix(adoptionInsights): improve test stability and reduce flakiness in Adoption Insights tests
  e2e-tests/playwright/e2e/plugins/adoption-insights/adoption-insights.spec.ts
  e2e-tests/playwright/support/pages/adoption-Insights.ts
  e2e-tests/playwright/support/pages/adoption-insights.ts
Labels: approved, lgtm

#3129 chore: remove resolution from dynamic-plugins
  dynamic-plugins/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3168 chore: add missing group headings in dynamic-plugins.default.yaml
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#2930 feat(scaffolder-and-catalog-import): Rename `Register an existing component` to `Import an existing Git repository`
  e2e-tests/playwright/e2e/audit-log/auditor-catalog.spec.ts
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/translations/catalog-import/catalog-import-en.ts
  packages/app/src/translations/catalog-import/catalog-import.ts
  packages/app/src/translations/scaffolder/scaffolder-en.ts
  packages/app/src/translations/scaffolder/scaffolder.ts
Labels: approved, lgtm

#3177 chore(deps): bump wrappers to latest .z plugin versions
  catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar.yaml
  catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3183 [release-1.7] feat(app-next): app-next initial spike
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  packages/app-next/.eslintrc.js
  packages/app-next/README.md
  packages/app-next/package.json
  packages/app-next/public/apple-touch-icon.png
  packages/app-next/public/favicon-96x96.png
  packages/app-next/public/favicon.ico
  packages/app-next/public/favicon.svg
  packages/app-next/public/index.html
  packages/app-next/public/robots.txt
  packages/app-next/public/site.webmanifest
  packages/app-next/public/web-app-manifest-192x192.png
  packages/app-next/public/web-app-manifest-512x512.png
  packages/app-next/src/App.test.tsx
  packages/app-next/src/App.tsx
  packages/app-next/src/index.tsx
  packages/app-next/src/setupTests.ts
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#3167 fix(marketplace): fix some marketplace entities
  catalog-entities/marketplace/packages/backstage-community-plugin-acr.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml
Labels: lgtm

#3182 fix(app-next): fix app-next dynamic plugin loading
  packages/app-next/package.json
Labels: approved, lgtm

#3170 fix(e2e): modify operator e2e tests to add the fab config
  .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
Labels: approved, lgtm

#3190 chore(homepage): update homepage version
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3203 chore(ci): enhance EKS e2e to use AWS DNS
  .ibm/pipelines/cluster/eks/aws.sh
  .ibm/pipelines/cluster/eks/eks-helm-deployment.sh
  .ibm/pipelines/cluster/gke/gcloud.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/eks-helm.sh
  .ibm/pipelines/jobs/eks-operator.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_EKS.yaml
Labels: approved, lgtm

#3212 fix(cherry-pick): e2e test fixes & CI fixes
  .ibm/images/Dockerfile
  .ibm/pipelines/cluster/aks/aks-helm-deployment.sh
  .ibm/pipelines/cluster/eks/aws.sh
  .ibm/pipelines/cluster/eks/eks-helm-deployment.sh
  .ibm/pipelines/cluster/gke/gcloud.sh
  .ibm/pipelines/cluster/gke/gke-helm-deployment.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/eks-helm.sh
  .ibm/pipelines/jobs/eks-operator.sh
  .ibm/pipelines/jobs/ocp-nightly.sh
  .ibm/pipelines/jobs/ocp-pull.sh
  .ibm/pipelines/jobs/upgrade.sh
  .ibm/pipelines/ocp-cluster-claim-login.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase-rbac_EKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase-rbac_GKE.yaml
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_EKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
  .ibm/pipelines/value_files/diff-values_showcase_upgrade.yaml
  .ibm/pipelines/value_files/values_showcase_1.5.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/adoption-insights/adoption-insights.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/smoke-test.spec.ts
  e2e-tests/playwright/support/pages/adoption-Insights.ts
  e2e-tests/playwright/support/pages/adoption-insights.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#3214 chore(e2e): fix double names
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
Labels: approved

#3172 feat(servicenow): added servicenow support for extensiosn plugin
  catalog-entities/marketplace/packages/all.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-servicenow-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-servicenow.yaml
  catalog-entities/marketplace/plugins/all.yaml
  catalog-entities/marketplace/plugins/servicenow.yaml
Labels: approved

#3221 chore: update form-data to fix CVE-2025-7783
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#3207 chore(e2e): fix: keycloak test case
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/keycloak/keycloak.ts
Labels: approved, lgtm

#3199 chore(deps): update extensions wrappers
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3224 chore: update rbac and quickstart
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-quickstart/package.json
  dynamic-plugins/yarn.lock
Labels: approved, lgtm

#3204 fix(servicenow): removed servicenow wrappers and added extension yaml files
  app-config.dynamic-plugins.yaml
  catalog-entities/marketplace/packages/all.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-servicenow-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-servicenow.yaml
  catalog-entities/marketplace/plugins/all.yaml
  catalog-entities/marketplace/plugins/servicenow.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/.eslintignore
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/.eslintrc.js
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-servicenow/turbo.json
  dynamic-plugins/yarn.lock
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
Labels: approved, lgtm

#3237 fix(e2e): fix quick start e2e and skip GitHub Happy path
  e2e-tests/playwright/e2e/custom-theme.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
Labels: approved, lgtm

#3239 [release-1.7] fix(lightspeed): update lightspeed plugins image and add installation section
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml
  catalog-entities/marketplace/plugins/lightspeed.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/yarn.lock
  e2e-tests/playwright/e2e/extensions.spec.ts
Labels: approved, lgtm

#3241 [release-1.7] fix(dynatrace-commercial): update dynatrace commercial images
  catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql-backend.yaml
  catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql.yaml
Labels: approved, lgtm

#3240 fix(dynatrace-commercial): update dynatrace commercial images
  catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql-backend.yaml
  catalog-entities/marketplace/packages/dynatrace-backstage-plugin-dql.yaml
Labels: approved, lgtm

#3245 chore(e2e): fix Kubernetes Actions plugin by adding wait (#3226)
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#3238 fix(lightspeed): update lightspeed plugins image and add installation section
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-lightspeed.yaml
  catalog-entities/marketplace/plugins/lightspeed.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/yarn.lock
  e2e-tests/playwright/e2e/extensions.spec.ts
Labels: approved, lgtm

#3226 chore(e2e): fix Kubernetes Actions plugin by adding wait
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#3247 chore: update OWNER file to remove coreydaley
  OWNERS
Labels: approved, lgtm
