Repository redhat-developer/rhdh, pull requests merged in 2025-09, with the labels that each got.

#3340 chore(ci): use nounset for CI scripts
  .gitignore
  .ibm/pipelines/cleanup.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/ocp-nightly.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2939 fix(e2e): adapt metrics test to k8s platform
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#3355 chore(deps): update sha.js to 2.4.12
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#3361 fix: remove redundant check and fix typo in pr-podman-push
  .github/workflows/pr-podman-push.yaml
Labels: approved, lgtm

#3367 chore(e2e): retries for bulk import test
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/support/pages/bulk-import.ts
  e2e-tests/playwright/utils/api-helper.ts
Labels: approved, lgtm

#3325 feat(i18n): add peristant language preference sync for authenticated users
  docs/customization.md
  packages/app/config.d.ts
  packages/app/src/apis.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/hooks/useLanguagePreference.test.ts
  packages/app/src/hooks/useLanguagePreference.ts
  packages/app/src/types/types.ts
  packages/app/src/utils/language/language.test.ts
  packages/app/src/utils/language/language.ts
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/modules/userSettings.ts
  yarn.lock
Labels: approved, lgtm

#3372 [release-1.3] chore: add authorize job for pr build image workflow
  .github/actions/check-author/action.yaml
  .github/workflows/pr-docker-build.yaml
Labels: approved, lgtm

#3348 fix(e2e): topology fix
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/support/pages/topology.ts
Labels: approved, lgtm

#3382 [release-1.7] chore(deps): update sha.js to 2.4.12, bump cipher-base from 1.0.4 to 1.0.6
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#3389 [release-1.7] fix(core-components): add missing translations for some core components
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/translations/core-components/core-components-en.ts
  packages/app/src/translations/core-components/core-components.ts
Labels: approved, lgtm

#3368 docs: add i18n guide for Playwright E2E tests
  docs/e2e-tests/e2e-i18n-guide.md
Labels: approved, lgtm

#3342 chore: add update-rpm-lockfile workflow
  .github/workflows/update-rpm-lockfile.yaml
Labels: approved, lgtm

#3418 fix: fix rpm lock update to actually run the command
  .github/workflows/update-rpm-lockfile.yaml
Labels: approved

#3439 chore: move .ibm into its own yarn workspace to fix downstream builds
  .github/workflows/pr.yaml
  .ibm/package.json
  .ibm/turbo.json
  .ibm/yarn.lock
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  package.json
  scripts/update-Dockerfile.sh
  turbo.json
  yarn.lock
Labels: approved, lgtm

#3141 chore(e2e): introduce tests from conditional rule isOwner
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
Labels: approved, lgtm

#3442 chore(e2e): introduce TSC check for e2e-tests
  .github/workflows/e2e-tests-lint.yaml
  docs/dynamic-plugins/debugging.md
  docs/proxy.md
  e2e-tests/.lintstagedrc.js
  e2e-tests/.lintstagedrc.json
  e2e-tests/package.json
Labels: approved, lgtm, Review effort 2/5, Tests

#3436 chore(marketplace): remove catalog and scaffolder integration collections
  catalog-entities/marketplace/plugins/all.yaml
  catalog-entities/marketplace/plugins/catalog-integrations.yaml
  catalog-entities/marketplace/plugins/scaffolder-integrations.yaml
Labels: approved, lgtm

#3438 chore: update axios to fix CVE-2025-58754
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#3437 [release-1.7] chore: update axios to fix CVE-2025-58754
  dynamic-plugins/yarn.lock
  yarn.lock
Labels: approved, lgtm

#3453 chore(ci): fix OCP 4.19 & GKE error handling
  .ibm/pipelines/cluster/gke/gcloud.sh
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#3456 feat(localization): adding localization for menuItems string coming through default config as well as added by user through app-config
  dynamic-plugins.default.yaml
  packages/app/src/App.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/Root/SidebarLogo.test.tsx
  packages/app/src/components/Root/SidebarLogo.tsx
  packages/app/src/consts.ts
  packages/app/src/hooks/useTranslation.ts
  packages/app/src/translations/rhdh/de.ts
  packages/app/src/translations/rhdh/es.ts
  packages/app/src/translations/rhdh/fr.ts
  packages/app/src/translations/rhdh/index.ts
  packages/app/src/translations/rhdh/it.ts
  packages/app/src/translations/rhdh/ref.ts
  packages/app/src/translations/search/search-de.ts
  packages/app/src/translations/search/search-en.ts
  packages/app/src/translations/search/search-es.ts
  packages/app/src/translations/search/search-fr.ts
  packages/app/src/translations/search/search-it.ts
  packages/app/src/translations/search/search.ts
  packages/app/src/translations/user-settings/user-settings-de.ts
  packages/app/src/translations/user-settings/user-settings-en.ts
  packages/app/src/translations/user-settings/user-settings-es.ts
  packages/app/src/translations/user-settings/user-settings-fr.ts
  packages/app/src/translations/user-settings/user-settings-it.ts
  packages/app/src/translations/user-settings/user-settings.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
  packages/plugin-utils/src/types.ts
  plugins/translation-backend/package.json
  yarn.lock
Labels: approved, lgtm

#3474 feat(quickstart): adding localization support for quickstart steps configured through dynamic-plugins.deafult or app-config
  dynamic-plugins.default.yaml
  packages/app/config.d.ts
Labels: approved, lgtm

#3429 chore(ci): update for job rename
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/reporting.sh
  .pr_agent.toml
  docs/auth.md
  docs/e2e-tests/CI.md
Labels: approved, Review effort 2/5

#3492 fix(e2e): github-happy-path workaround for failing test
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
Labels: approved, lgtm
