Repository redhat-developer/rhdh, pull requests merged in 2025-01, with the labels that each got.

#2141 chore(ci-doc): documentation for RHDH setup in ephemeral env using OCP.
  .ibm/pipelines/README.md
Labels: approved, lgtm

#2142 chore(e2e): fix bulk import test case
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2085 chore(wrapper): add kubernetes-actions plugin wrapper
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/.eslintignore
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/src/index.ts
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/tsconfig.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#2083 chore(deps): [release-1.3] fix CVE-2024-55565
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity/dist-dynamic/yarn.lock
  dynamic-plugins/wrappers/pagerduty-backstage-plugin-backend-dynamic/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#2086 chore(deps): [release-1.4] fix CVE-2024-55565
  yarn.lock
Labels: approved, lgtm

#2145 chore(ci): use ephemeral AKS cluster with fallback
  .ibm/pipelines/jobs/aks.sh
Labels: approved, lgtm, ok-to-test

#2146 chore(ci): fix droute failing to send results on 1st try
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2131 chore(e2e): cleanup operator e2e script and config
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2152 chore(ci): fix droute error handling for nightly
  .ibm/pipelines/utils.sh
Labels: approved, lgtm, ok-to-test

#2158 chore(ci): improvements & fix for Data Router
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2157 chore(ci): improvements & fix for Data Router
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2172 chore(ci): refactor hardcoded backstage-showcase in e2e tests
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/dynamic-homepage-and-sidebar-config.yaml
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2179 chore(deps): [release-1.4] Bump path-to-regexp to v0.1.12 to fix CVE-2024-52798
  packages/backend/package.json
  plugins/dynamic-plugins-info-backend/package.json
  plugins/licensed-users-info-backend/package.json
  plugins/scalprum-backend/package.json
  yarn.lock
Labels: approved

#2175 chore(plugins): bump dynamic plugin wrappers...
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-quay/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-regex-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-sonarqube-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-sonarqube-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-sonarqube/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-datadog/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-jira/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-security-insights/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request-dynamic/package.json
  dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-utils-dynamic/package.json
  scripts/update-dynamic-plugins-wrappers.sh
  yarn.lock
Labels: approved

#2166 chore(e2e): enable scaffolder processor for GKE and AKS tests
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
Labels: approved, lgtm

#2135 chore(e2e): skip PR build for changes limited to e2e folder or existing image
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2184 chore(CI): fix typo in folder name in CI build condition check
  .github/workflows/pr-build-image.yaml
Labels: approved

#2189 chore: add renovate config validator to CI
  .github/workflows/renovate-checks.yaml
Labels: approved, lgtm

#2174 chore(migration): refactor hardcoded repo and images (#2172, #2181)
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/postgres-db/values-showcase-postgres.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/package.json
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
  e2e-tests/playwright/utils/APIEndpoints.ts
Labels: approved, lgtm

#2186 chore: update opentelemetry/host-metrics to fix CVE-2024-56334
  packages/backend/package.json
  yarn.lock
Labels: approved

#2192 Cherry pick 1.3 showcase refactor
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/support/pages/CatalogImport.ts
Labels: approved, lgtm

#2196 chore(e2e): temporarily disable a failing test
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
Labels: approved, lgtm

#2036 chore(ci): build multiplatform next container image
  .github/actions/docker-build/action.yaml
  .github/actions/get-sha/action.yml
  .github/workflows/next-build-image.yaml
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2200 chore: update GitHub Actions workflow to skip builds for changes in specific folders
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2201 chore(e2e): fix test results not found issue in nightly job
  .ibm/pipelines/jobs/periodic.sh
Labels: approved, lgtm

#2203 chore(e2e): fix backstage operator being deployed before its ready
  .ibm/pipelines/jobs/operator.sh
Labels: approved, lgtm

#2191 chore(e2e): [Test automation] Verify Topology is a supported plugin and E2E scenario follow-up
  .ibm/pipelines/resources/topology_test/topology-test.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/support/pages/topology.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm, ok-to-test

#2208 chore(e2e): skip topology plugin test on k8s clusters
  .ibm/pipelines/utils.sh
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#2197 chore(e2): rhidp-5439 - [e2e] container "backstage-backend" in pod ... is waiting to start: PodInitializing
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
  e2e-tests/playwright/e2e/audit-log/log-utils.ts
Labels: approved, lgtm

#2209 test(e2e): adjust selectors for rbac test for 1.4
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2155 test(e2e): adjust selectors for rbac test
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2211 chore: replace-showcase-references
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2221 chore: update renovate config
  .github/renovate.json
Labels: approved, lgtm, do-not-merge/work-in-progress

#2214 test(e2e): make ocm non serial
  e2e-tests/playwright/e2e/plugins/ocm.spec.ts
Labels: approved, lgtm

#2231 chore(e2e): skip audit log test
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
Labels: approved, lgtm

#2156 chore(wrapper): add wrapper for marketplace frontend, backend and catalog-backend-module plugins
  .rhdh/docker/Dockerfile
  app-config.dynamic-plugins.yaml
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/.eslintignore
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/.eslintignore
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/.eslintignore
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#2241 docs: replace more showcase references with RHDH
  CONTRIBUTING.md
  docs/audit-log.md
  docs/auth.md
  docs/dynamic-plugins/debugging.md
  docs/e2e-tests/CI.md
  docs/index.md
  docs/monitoring-and-logging.md
  docs/patch-package.md
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  scripts/update-backstage.mjs
Labels: approved, lgtm

#2240 chore: create catalog-info.yaml and entity for the rhdh-team
  catalog-entities/groups.yaml
  catalog-entities/groups/rhdh-team.yaml
  catalog-info.yaml
  docs/mkdocs.yml
Labels: approved, lgtm

#2223 chore(test): fix quay tests and improve RBAC testing for scaffolding
  .github/workflows/pr-build-image.yaml
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/postgres-db/postgres.yaml
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2232 chore(ci): label stale PRs and clean its cache
  .github/workflows/cache-cleanup.yaml
  .github/workflows/stale.yaml
Labels: approved, lgtm

#2168 feat(global-header): added mount points for global header
  .rhdh/docker/Dockerfile
  app-config.dynamic-plugins.yaml
  docker/Dockerfile
  docs/dynamic-plugins/frontend-plugin-wiring.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/.eslintignore
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/tsconfig.json
  packages/app/src/components/Root/ApplicationHeaders.tsx
  packages/app/src/components/Root/Root.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#2218 chore(ci): build images from tags, build next nightly
  .github/workflows/next-build-image.yaml
Labels: approved, lgtm

#2182 docs(dynamic-plugins): update todo plugin instructions and add TypeScript compilation step
  docs/dynamic-plugins/index.md
Labels: approved, lgtm

#2244 chore(e2e): fix quay image validation
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2245 chore(e2e): add delay after template registration to prevent catalog open failure
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2247 chore: git workflow build image
  .github/workflows/pr-build-image.yaml
Labels: approved

#2235 chore: [release 1.4] update dockerfile images
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2251 chore: [release-1.3] update approvers
  OWNERS
Labels: approved, lgtm

#2249 chore: fix PR builder so when new commits are added, new builds happen (check for pr-123-SHA instead of pr-123)
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2236 chore: [release-1.3] update dockerfile images
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: lgtm

#2252 chore(deps): bump nanoid to 3.3.8 to fix CVE-2024-55565
  yarn.lock
Labels: approved, lgtm

#2257 chore: update python version - RHIDP-5582 [release-1.4]
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2100 fix(rbac): fix edit rbac operations for high availability
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2260 chore(ci): fix nightly image build by add missing step to set REF_NAME based on branch
  .github/workflows/next-build-image.yaml
Labels: approved, lgtm

#2267 fix(rbac): fix edit rbac operations for high availability
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2266 chore: update catalog-info and docs title
  app-config.example.yaml
  app-config.yaml
  catalog-info.yaml
  mkdocs.yaml
  packages/app/public/manifest.json
Labels: approved, lgtm

#2265 chore(e2e-docs): add instructions for triggering optional nightly jobs on PRs
  docs/e2e-tests/CI.md
Labels: approved, lgtm

#2264 chore(e2e): cherry-pick #2245 - add delay after template registration to prevent catalog open failure
  e2e-tests/playwright/e2e/catalog-scaffoldedfromLink.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2237 chore(e2e): fix and enable bulk import test
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Labels: approved, lgtm

#2258 chore(ci): ignore sanity deployment in periodic job
  .ibm/pipelines/jobs/periodic.sh
Labels: approved, lgtm

#2280 chore: disable renovate updates from rhdh-plugins
  .github/renovate.json
Labels: approved, lgtm

#2282 chore(e2e): fix quay flaky test
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2239 test(e2e): first Plugin Marketplace test
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugin-marketplace.spec.ts
  e2e-tests/playwright/utils/navbar.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#1982 docs(e2e): examples for e2e tests
  docs/e2e-tests/README.md
  docs/e2e-tests/examples.md
  e2e-tests/README.md
Labels: approved, lgtm, Stale

#2215 chore(e2e): [e2e] Fix and Enable topoloy test case on AKS and GKE
  .ibm/pipelines/resources/topology_test/topology-test-ingress.yaml
  .ibm/pipelines/resources/topology_test/topology-test-route.yaml
  .ibm/pipelines/resources/topology_test/topology-test.yaml
  .ibm/pipelines/utils.sh
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm, ok-to-test

#2250 chore(e2e): fix a module which has no default export
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#2284 chore: linking index.html to index.html.tmpl
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2242 chore(ci): update for e2e on new GKE and ephemeral AKS cluster
  .ibm/pipelines/cluster/aks/deployment.sh
  .ibm/pipelines/cluster/gke/deployment.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/aks.sh
  .ibm/pipelines/jobs/gke.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
Labels: approved, lgtm

#2289 chore(ci): change service account token on GKE
  .ibm/pipelines/jobs/gke.sh
Labels: approved, lgtm

#2268 chore: misc wrapper fixes
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/turbo.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
Labels: approved, lgtm

#2288 chore(e2e): fix bulk import and topology flaky tests
  e2e-tests/playwright/support/pages/bulk-import.ts
  e2e-tests/playwright/support/pages/topology.ts
  e2e-tests/playwright/utils/api-helper.ts
Labels: approved, lgtm, ok-to-test

#2295 chore(ci): skip rds tests in 1.4
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#2292 chore(ci): clean up from long-running AKS & fix probes RBAC
  .ibm/pipelines/cluster/aks/az.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/aks.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/value_files/diff-values_showcase-rbac_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase-rbac_GKE.yaml
  .ibm/pipelines/value_files/diff-values_showcase_AKS.yaml
  .ibm/pipelines/value_files/diff-values_showcase_GKE.yaml
  docs/e2e-tests/CI.md
Labels: approved, lgtm

#2291 chore: [release-1.3] fix CVE-2025-22150
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2290 chore: [release-1.4] fix CVE-2025-22150
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2243 chore: remove janus links from homepage
  e2e-tests/playwright/e2e/plugins/quick-access-and-tech-radar.spec.ts
  packages/app/public/homepage/data.json
  packages/app/public/homepage/icons/icons8/external-blog-copywriting-itim2101-lineal-itim2101.png
  packages/app/public/homepage/icons/icons8/external-mailing-list-information-technology-solid-solidglyph-m-oki-orlando.png
  packages/app/public/homepage/icons/icons8/github.png
  packages/app/public/homepage/icons/icons8/slack-new.png
  packages/app/public/homepage/icons/icons8/tear-off-calendar.png
  packages/app/public/homepage/icons/icons8/web.png
  packages/app/public/homepage/icons/icons8/youtube-play.png
Labels: approved, lgtm
