Repository redhat-developer/rhdh, pull requests merged in 2025-03, with the labels that each got.

#2477 [release-1.5] chore(e2e-tests): add e2e tests for header mount points
  .ibm/pipelines/resources/config_map/dynamic-global-header-config.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/e2e/header-mount-points.spec.ts
Labels: approved, lgtm

#2473 test: update redis tests
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Labels: approved, lgtm

#2439 chore(build): update to nodejs 22
  .github/workflows/pr.yaml
  .nvmrc
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  e2e-tests/package.json
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#2436 chore(e2e): add/move Github login specific test case to github Auth provider test suite.
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/support/pages/catalog-import.ts
  e2e-tests/playwright/utils/common.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2487 chore(test): fix redis test
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
Labels: approved, lgtm

#2482 chore(rbac): update rbac backend plugin
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2470 fix: show external plugins as enabled
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
Labels: approved, lgtm

#2493 chore(e2e): fix topology plugin test
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm

#2406 chore(deps): update plugins with new k8s-client, update plugin annotator
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-quay/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2492 chore(rbac): update RBAC frontend plugin
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  yarn.lock
Labels: approved, lgtm

#2504 chore(deps): revert to using mcr.microsoft.com/playwright:v1.48.2-jammy to unblock 1.5 builds -- must stay on Node 20 (RHIDP-6244)
  .ibm/images/Dockerfile
  .ibm/images/README
Labels: approved, lgtm

#2500 chore(deps): update plugins with new k8s-client, update plugin annotator
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-quay/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  packages/backend/package.json
  yarn.lock
Labels: approved, lgtm

#2358 feat(extensions): rename plugins to extensions, enable marketplace plugin by default and show it as catalog on the new renamed page
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  e2e-tests/playwright/e2e/extensions.spec.ts
  e2e-tests/playwright/e2e/plugin-marketplace.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/utils/navbar.ts
  packages/app/src/App.tsx
  plugins/dynamic-plugins-info/app-config.dynamic.yaml
  plugins/dynamic-plugins-info/app-config.janus-idp.yaml
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoPage.tsx
  plugins/dynamic-plugins-info/src/index.ts
  plugins/dynamic-plugins-info/src/plugin.ts
  yarn.lock
Labels: approved

#2488 [release-1.5] feat(extensions): rename plugins to extensions, enable marketplace plugin by default and show it as catalog on the new renamed page
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  e2e-tests/playwright/e2e/extensions.spec.ts
  e2e-tests/playwright/e2e/plugin-marketplace.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/utils/navbar.ts
  packages/app/src/App.tsx
  plugins/dynamic-plugins-info/app-config.dynamic.yaml
  plugins/dynamic-plugins-info/app-config.janus-idp.yaml
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoPage.tsx
  plugins/dynamic-plugins-info/src/index.ts
  plugins/dynamic-plugins-info/src/plugin.ts
  yarn.lock
Labels: approved

#2509 chore(e2e): fix flaky e2e tests
  e2e-tests/playwright/e2e/audit-log/log-utils.ts
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
Labels: approved, lgtm

#2497 fix(init): ensure the config is always built
  docker/install-dynamic-plugins.py
Labels: approved, lgtm

#2508 chore: update plugin-catalog-backend-module-keycloak version
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2519 test(e2e): add wait for animations
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2521 test(e2e): add waitForAnimations uihelper main
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2425 fix: catalog entity tabs order
  docs/dynamic-plugins/frontend-plugin-wiring.md
  packages/app/config.d.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/catalog/EntityPage/DynamicEntityTab.tsx
  packages/app/src/components/catalog/EntityPage/EntityPage.tsx
  packages/app/src/components/catalog/EntityPage/utils.test.tsx
  packages/app/src/components/catalog/EntityPage/utils.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
Labels: approved, lgtm

#2507 [release-1.5] chore(e2e): add RHSSO sub claim resolvers to auth e2e tests
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Labels: approved, lgtm

#2524 chore(e2e): rhidp-6297 Automate E2E Runner Image Build and Push to Quay via GitHub Actions
  .github/workflows/push-e2e-runner.yaml
  .ibm/images/README
Labels: approved, lgtm

#2520 docs: create redis-setup.md
  docs/redis-setup.md
Labels: approved, lgtm

#2535 fix(marketplace): bump catalog backend module for marketplace
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  plugins/dynamic-plugins-info/app-config.dynamic.yaml
  yarn.lock
Labels: approved, lgtm

#2534 chore(e2e): rhidp-6330 Fix Failing E2E Test - Nightly - Rbac - Edit users and groups and update policies of a role from the overview page
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2408 fix(favicon): re-embed dynamic favicon into index.html
  packages/app/public/index.html
  packages/app/src/components/AppBase/AppBase.tsx
Labels: approved, lgtm

#2451 chore(e2e): add RHSSO sub claim resolvers to auth e2e tests
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Labels: approved, lgtm, ok-to-test

#2542 fix(marketplace): bump catalog-backend-module
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2546 chore(e2e): install pinned version of yarn v3 using corepack, instead of v1
  .ibm/images/Dockerfile
Labels: approved, lgtm

#2551 chore(deps): update minimum node version to 22, now that we're using a node 22 dockerfile to build RHDH
  .github/workflows/pr.yaml
  package.json
Labels: approved

#2568 chore(e2e): revert chart version update used for e2e test
  .ibm/pipelines/env_variables.sh
Labels: approved, lgtm

#2565 test: update env variable
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/value_files/values_showcase-auth-providers.yaml
  e2e-tests/playwright/utils/helper.ts
Labels: approved, lgtm

#2571 fix(docs): updated customization.md
  docs/customization.md
  docs/index.md
Labels: approved, lgtm

#2321 chore(ci): run cache cleanup workflow on pull_request_target
  .github/workflows/cache-cleanup.yaml
Labels: approved, lgtm

#2572 fix: make FAB plugin RH supported
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
Labels: approved, lgtm

#2598 fix(e2e): config namespace issue in upgrade test
  .ibm/pipelines/jobs/upgrade.sh
  .ibm/pipelines/utils.sh
Labels: lgtm

#2606 chore(e2e): add marketplace e2e tests to rhdh
  e2e-tests/playwright/e2e/extensions.spec.ts
  e2e-tests/playwright/support/pages/extensions.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2532 chore(e2e): add tests for includeTransitiveGroupOwnership config with RBAC
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  catalog-entities/e2e-test-resources/rbac-transitive-parent-ownership.yaml
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2550 feat(sidebar): sidebar items can be removed by setting enabled:false
  docs/dynamic-plugins/frontend-plugin-wiring.md
  packages/app/config.d.ts
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfigFrontend.ts
Labels: approved, lgtm

#2612 chore(e2e): add tests to 'sessionDuration' auth config
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#2547 chore(deps): reinstall @backstage/plugin-api-docs to fix node-gyp errors in tree-sitter
  yarn.lock
Labels: approved, lgtm

#2574 feat: renaming `Create` to `Self-service`
  .ibm/pipelines/resources/config_map/dynamic-global-header-config.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-header.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/utils/navbar.ts
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/catalog/translations/catalog-en.ts
  packages/app/src/components/catalog/translations/catalog.ts
  packages/app/src/consts.ts
  yarn.lock
Labels: approved, lgtm

#2566 fix(sidebar): wrap long menu item label in sidebar
  packages/app/src/components/Root/Root.tsx
Labels: approved, lgtm

#2609 test(e2e): middleware tests
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/resources/config_map/dynamic-plugins-config.yaml
  .ibm/pipelines/resources/rhdh-operator/rhdh-start.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/e2e/plugins/middleware.spec.ts
Labels: approved, lgtm

#2613 chore: force transitive update of cpu-features
  yarn.lock
Labels: approved, lgtm

#2564 feat(user-settings): allow overriding build info in the user settings page
  .github/actions/get-sha/action.yml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docs/customization.md
  e2e-tests/playwright/e2e/plugins/user-settings-info-card.spec.ts
  packages/app/config.d.ts
  packages/app/src/build-metadata.json
  packages/app/src/components/UserSettings/InfoCard.test.tsx
  packages/app/src/components/UserSettings/InfoCard.tsx
  packages/app/src/types/types.ts
  scripts/update-metadata.mjs
Labels: approved, lgtm

#2608 fix(docs): update readme with steps to hide sidebar search
  docs/customization.md
  docs/images/sidebar-search-hidden.png
Labels: approved, lgtm

#2621 chore(ci): fix droute error handling
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2614 chore(deps): backstage 1.36 plugin updates
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-azure-devops-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-azure-devops/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-dynatrace/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-github-actions/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-github-issues/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jenkins-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jenkins/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-lighthouse/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-quay/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-quay-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-regex-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-sonarqube-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tech-radar/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  packages/app/package.json
  packages/backend/package.json
  plugins/licensed-users-info-backend/package.json
  yarn.lock
Labels: approved, lgtm

#2626 chore(deps): update bulk import backend plugin
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2615 fix: add oauth2ProxyUserHeaderMatchingUserEntityName auth resolver
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/modules/authResolvers.ts
Labels: approved, lgtm

#2627 chore: update keycloak version for 1.6
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2633 chore: fix CVE-2025-29775
  yarn.lock
Labels: approved, lgtm

#2634 chore: update owners file
  OWNERS
Labels: approved, lgtm

#2630 chore: [release-1.5] update dockerfile images
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved, lgtm

#2578 [release-1.5] fix(marketplace): add MUI v5 workaround to marketplace wrapper, similar to other plugins
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/src/index.ts
  yarn.lock
Labels: Stale

#2552 chore(argocd): update Red Hat and RoadieHQ wrappers
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd-backend-dynamic/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#2643 Update workflow to use SHORT_SHA from environment variables
  .github/actions/check-image-and-changes/action.yaml
  .github/workflows/pr-build-image.yaml
Labels: approved

#2632 chore(deps): update topology plugin
  dynamic-plugins/wrappers/backstage-community-plugin-topology/package.json
  yarn.lock
Labels: approved, lgtm

#2637 chore(marketplace): various catalog metadata fixes
  catalog-entities/marketplace/plugins/3scale.yaml
  catalog-entities/marketplace/plugins/ansible-plugin.yaml
  catalog-entities/marketplace/plugins/azure-container-registry.yaml
  catalog-entities/marketplace/plugins/azure-repositories.yaml
  catalog-entities/marketplace/plugins/backstage-community-plugin-quay.yaml
  catalog-entities/marketplace/plugins/datadog.yaml
  catalog-entities/marketplace/plugins/extensions.yaml
  catalog-entities/marketplace/plugins/github-issues.yaml
  catalog-entities/marketplace/plugins/github-pull-requests.yaml
  catalog-entities/marketplace/plugins/github-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/jira.yaml
  catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml
  catalog-entities/marketplace/plugins/lighthouse.yaml
  catalog-entities/marketplace/plugins/nexus-repository-manager.yaml
  catalog-entities/marketplace/plugins/openshift-cluster-manager.yaml
  catalog-entities/marketplace/plugins/roadie-argocd.yaml
  catalog-entities/marketplace/plugins/topology.yaml
Labels: approved, lgtm

#2649 chore(marketplace): rename boilerplate
  catalog-entities/marketplace/plugins/1-boilerplate.yaml.sample
  catalog-entities/marketplace/plugins/orchestrator.yaml
Labels: lgtm

#2651 chore(marketplace): convert categories to an array to restore missing plugins
  catalog-entities/marketplace/plugins/datadog.yaml
  catalog-entities/marketplace/plugins/extensions.yaml
  catalog-entities/marketplace/plugins/lighthouse.yaml
  catalog-entities/marketplace/plugins/openshift-cluster-manager.yaml
Labels: lgtm

#2622 chore(ci): droute with bastion pod - switch contexts and enhanced waiting in retries (#2599)
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
Labels: approved, lgtm

#2648 chore: fix CVE-2025-29775
  yarn.lock
Labels: approved, lgtm

#2653 chore(deps): update to xml-crypto@npm:6.0.1...
  yarn.lock
Labels: approved, lgtm

#2658 chore(e2e): fix failing e2e tests - Operator Postgres DB with TLS
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
Labels: approved, lgtm

#2659 chore(e2e): remove wrong JOB_NAME override in openshift-ci-tests.sh
  .ibm/pipelines/openshift-ci-tests.sh
Labels: approved, lgtm

#2646 [release-1.5] fix(favicon): re-embed dynamic favicon into index.html
  packages/app/public/index.html
  packages/app/src/components/AppBase/AppBase.tsx
Labels: approved, lgtm
