Repository redhat-developer/rhdh, pull requests merged in 2025-10, with the labels that each got.

#3483 feat(translations): translate rhdh, backstage core and community plugins and components
  .dockerignore
  .rhdh/docker/Dockerfile
  docker/Dockerfile
  docs/customization.md
  e2e-tests/playwright/e2e/localization/locale-test.spec.ts
  packages/app/config.d.ts
  packages/app/package.json
  packages/app/src/build-metadata.json
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/ScalprumRoot.tsx
  packages/app/src/components/ErrorPages/NotFoundErrorPage.tsx
  packages/app/src/components/ErrorPages/errorButtons/ContactSupportButton.tsx
  packages/app/src/components/ErrorPages/errorButtons/GoBackButton.tsx
  packages/app/src/components/SignInPage/SignInPage.tsx
  packages/app/src/components/UserSettings/GeneralPage.tsx
  packages/app/src/components/UserSettings/InfoCard.tsx
  packages/app/src/components/catalog/EntityPage/DiagramTabContent.tsx
  packages/app/src/components/learningPaths/LearningPathsPage.tsx
  packages/app/src/components/search/SearchPage.tsx
  packages/app/src/translations/rhdh/de.ts
  packages/app/src/translations/rhdh/es.ts
  packages/app/src/translations/rhdh/fr.ts
  packages/app/src/translations/rhdh/it.ts
  packages/app/src/translations/rhdh/ref.ts
  packages/app/src/types/types.ts
  packages/app/src/utils/test/TestRoot.tsx
  packages/app/src/utils/translations/fetchOverrideTranslations.ts
  packages/app/src/utils/translations/staticTranslationConfigs.ts
  packages/app/src/utils/translations/translationResourceGenerator.ts
  packages/app/src/utils/translations/translationResourceProcessor.ts
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/plugin-utils/src/context/DynamicRootContext.test.tsx
  packages/plugin-utils/src/context/DynamicRootContext.tsx
  packages/plugin-utils/src/hooks/useDynamicPlugin.ts
  packages/plugin-utils/src/hooks/useDynamicPlugins.test.tsx
  packages/plugin-utils/src/types.ts
  plugins/translation-backend/.eslintrc.js
  plugins/translation-backend/.lintstagedrc.json
  plugins/translation-backend/.prettierignore
  plugins/translation-backend/.prettierrc.js
  plugins/translation-backend/README.md
  plugins/translation-backend/package.json
  plugins/translation-backend/src/index.ts
  plugins/translation-backend/src/plugin.ts
  plugins/translation-backend/src/service/router.test.ts
  plugins/translation-backend/src/service/router.ts
  plugins/translation-backend/src/utils.test.ts
  plugins/translation-backend/src/utils.ts
  plugins/translation-backend/tsconfig.json
  plugins/translation-backend/turbo.json
  translations/backstage-plugins-translations_v1.8_s3280-fr-C.json
  translations/community-plugins-translations_v1.8_s3280-fr-C.json
  yarn.lock
Labels: approved, lgtm

#3500 chore: remove dominika and mitesh as default reviewers
  OWNERS
Labels: approved, lgtm

#3501 chore: disable flaky tests
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm, Tests, Review effort 1/5

#3488 chore(deps): bump adoption insights plugins version
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-adoption-insights/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic/package.json
  dynamic-plugins/yarn.lock
  e2e-tests/playwright/e2e/plugins/adoption-insights/adoption-insights.spec.ts
  e2e-tests/playwright/support/pages/adoption-insights.ts
Labels: approved, lgtm

#3412 feat(header): adding translation support in config
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#3508 chore(e2e): link Jira to fixme tests skipped in #3501
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
Labels: approved, lgtm, Review effort 2/5, Tests

#3415 fix(catalog-entities): update lightspeed.yaml
  catalog-entities/marketplace/plugins/lightspeed.yaml
Labels: approved, lgtm
