Repository redhat-developer/rhdh, pull requests merged in 2025-08, with the labels that each got.

#3091 feat(optimizations): add plugin redhat-resource-optimizations to marketplace
  catalog-entities/marketplace/plugins/optimizations.yaml
Labels: approved, lgtm

#3242 chore(ci): switch PR workflow from pull_request to pull_request_target for secrets
  .github/workflows/pr.yaml
Labels: approved

#3284 test: skip gitlab discovery UI tests due to RHDHBUGS-1977
  e2e-tests/playwright/e2e/plugins/gitlab/gitlab-discovery.spec.ts
Labels: approved, lgtm

#3274 fix(extensions): remove verified badge of servicenow tile
  catalog-entities/marketplace/plugins/servicenow.yaml
Labels: approved, lgtm

#3189 chore(e2e): add e2e tests for software template versioning
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/scaffolder-backend-module-annotator.spec.ts
  e2e-tests/playwright/support/pages/adoption-insights.ts
Labels: approved, lgtm

#3304 chore: declare production support for msgraph plugin
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
Labels: approved, lgtm

#3267 fix: update namespace validation to support any version in cluster login script
  .ibm/pipelines/README.md
  .ibm/pipelines/ocp-cluster-claim-login.sh
Labels: Stale

#3314 chore(e2e): fix Operator Installation Failure - No Endpoints Available for Webhook
  .ibm/pipelines/utils.sh
Labels: approved

#3315 chore: fix CVE-2025-9288 and CVE-2025-9287
  yarn.lock
Labels: approved, lgtm

#3330 chore(ci): separate Data Router step (#3326)
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/reporting.sh
  .ibm/pipelines/utils.sh
  e2e-tests/data_router/data_router_metadata_template.json
Labels: approved

#3266 chore: add hermeto builds to PR Builds (New)
  .dockerignore
  .github/actions/docker-build/action.yaml
  .github/workflows/podman-push.yaml
  .github/workflows/pr-build-image.yaml
  rpms.in.yaml
  rpms.lock.yaml
Labels: approved, lgtm

#3253 docs: update README.md with correct information where to report Bugs
  README.md
Labels: approved, lgtm

#3347 chore: add Zaperex as approver for prow
  OWNERS
Labels: approved, lgtm

#3319 feat(i18n): enable localization framework in RHDH
  docs/customization.md
  docs/dynamic-plugins/frontend-plugin-wiring.md
  packages/app/config.d.ts
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/ScalprumRoot.tsx
  packages/app/src/types/types.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.test.ts
  packages/app/src/utils/dynamicUI/extractDynamicConfig.ts
Labels: approved, lgtm

#3310 feat: update learning-path card for "How to create a PyTorch model"
  packages/app/public/learning-paths/data.json
Labels: approved, lgtm, ok-to-test
