Repository redhat-developer/rhdh, pull requests merged in 2025-02, with the labels that each got.

#2303 chore: remove backstage-plugin-aap-backend
  .ibm/pipelines/value_files/sanity-check-plugins.yaml
  .rhdh/docker/Dockerfile
  README.md
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/.eslintignore
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/.eslintrc.js
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/package.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/src/index.ts
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/tsconfig.json
  dynamic-plugins/wrappers/janus-idp-backstage-plugin-aap-backend-dynamic/turbo.json
  plugins/dynamic-plugins-info-backend/__fixtures__/data.ts
  plugins/dynamic-plugins-info-backend/__fixtures__/expected_result.ts
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#2300 chore: update renovate to better handle winston, react-router-dom, ya…
  .github/renovate.json
Labels: approved, lgtm

#2309 feat(acr): update acr plugin to 1.10.0
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  yarn.lock
Labels: lgtm

#2293 feat(homepage): update plugin that includes Backstage 1.35.0 and latest home page improvements
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  yarn.lock
Labels: lgtm

#2312 feat(fab): add new mountpoints support for providers and listeners (fixed CI issue)
  .rhdh/docker/Dockerfile
  app-config.dynamic-plugins.yaml
  docker/Dockerfile
  docs/dynamic-plugins/frontend-plugin-wiring.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/.eslintignore
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/src/index.ts
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/tsconfig.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/turbo.json
  packages/app/src/components/AppBase/AppBase.tsx
  packages/app/src/components/Root/ApplicationListener.tsx
  packages/app/src/components/Root/ApplicationProvider.tsx
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: lgtm

#2020 chore: add additional OIDC auth resolvers
  docs/auth.md
  docs/ping-identity-oidc-setup.md
  packages/backend/package.json
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/modules/authResolvers.ts
  yarn.lock
Labels: approved, lgtm

#2207 chore(e2e): test infra setup for osd nightly job using helm
  .ibm/pipelines/cluster/osd-gcp/create-osd.sh
  .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
  .ibm/pipelines/openshift-ci-tests.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/verify-redis-cache.spec.ts
  e2e-tests/playwright/support/pages/catalog-import.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2319 chore(e2e): skip bulk import test case on osd helm nighlty job.
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
Labels: approved, lgtm

#2315 chore: update keycloak plugin version
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  yarn.lock
Labels: approved, lgtm, ok-to-test

#2329 test: auth providers periodic job configuration
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/auth-providers.sh
  .ibm/pipelines/openshift-ci-tests.sh
  e2e-tests/package.json
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/utils/helper.ts
  e2e-tests/playwright/utils/logger.ts
Labels: approved, lgtm, ok-to-test

#2332 refactor: replace janus-idp/rbac-common dep with updated BCP/rbac-common
  packages/app/package.json
  packages/app/src/components/Root/Root.tsx
  yarn.lock
Labels: approved, lgtm

#2210 feat: support configuration to include transient group ownership during auth
  docs/auth.md
  docs/dynamic-plugins/export-derived-package.md
  packages/app/config.d.ts
  packages/backend/package.json
  packages/backend/src/modules/authProvidersModule.test.ts
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/transientGroupOwnershipResolver.test.ts
  packages/backend/src/transientGroupOwnershipResolver.ts
  yarn.lock
Labels: approved, lgtm

#2341 chore: enable renovate on janus cli updates
  .github/renovate.json
Labels: approved, lgtm

#2328 fix: fix image-stream in nightly jobs
  .ibm/pipelines/utils.sh
Labels: approved, lgtm, ok-to-test

#2318 chore(ci): update K8s nightly e2e tests for slower clusters
  .ibm/pipelines/jobs/aks.sh
  .ibm/pipelines/jobs/gke.sh
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/smoke-test.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2344 chore(e2e): fix gcp osd operator job
  .ibm/pipelines/cluster/osd-gcp/destroy-osd.sh
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2285 feat: avoid dynamic-plugins writing conflicts
  docker/install-dynamic-plugins.py
  docs/dynamic-plugins/installing-plugins.md
Labels: approved, lgtm

#2352 [release-1.3] feat: avoid dynamic-plugins writing conflicts (#2285)
  docker/install-dynamic-plugins.py
  showcase-docs/dynamic-plugins.md
Labels: approved, lgtm

#2336 chore: update support-versions to 1.35.1
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
Labels: approved, lgtm

#2271 chore(e2e): incorporate tls tests into showcase-runtime
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/resources/postgres-db/values-showcase-postgres.yaml
  .ibm/pipelines/utils.sh
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/configuration-test/config-map.spec.ts
  e2e-tests/playwright/e2e/verify-tls-config-health-check.spec.ts
Labels: approved, lgtm

#2353 feat: add VisitListener to home page plugin
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#2355 fix: update fab wrapper
  app-config.dynamic-plugins.yaml
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
  yarn.lock
Labels: approved, lgtm

#2322 chore: update rbac plugins
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/ui-helper.ts
  packages/app/package.json
  packages/backend/package.json
  plugins/licensed-users-info-backend/package.json
  yarn.lock
Labels: approved, lgtm

#2330 chore(deps): use some plugins updated to backstage 1.35
  dynamic-plugins/wrappers/backstage-community-plugin-3scale-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-analytics-provider-segment/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-ocm/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-regex-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-scaffolder-backend-module-sonarqube-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2366 chore: update GroupOwnershipResolver and config name
  docs/auth.md
  packages/app/config.d.ts
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/transitiveGroupOwnershipResolver.test.ts
  packages/backend/src/transitiveGroupOwnershipResolver.ts
Labels: approved, lgtm

#2364 chore(e2e): fix rbac `users, groups` with regex
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/page-obj.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  e2e-tests/playwright/support/pages/home-page.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2357 chore(e2e): update k8s specific config
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/bulk-import.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  e2e-tests/playwright/utils/common.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2389 chore(ci): use arm VM (ubuntu-24.04-arm) for building arm images
  .github/workflows/next-build-image.yaml
Labels: approved, lgtm

#2397 chore(ci): don't fail pipeline when `droute` error
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2377 fix(sidebar): added config for disable search menu item
  packages/app/config.d.ts
  packages/app/src/components/Root/Root.tsx
Labels: approved, lgtm, ok-to-test

#2407 fix: fix auth providers timeouts
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
Labels: approved, lgtm

#2248 chore(e2e): refactor periodic pipeline to include sanity plugins check
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/jobs/periodic.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/sanity-check-plugins.yaml
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
Labels: approved, lgtm

#2383 chore(e2e): rhidp-5634 Update audit log messages for e2e tests.
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/utils/quay/quay.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2263 feat(global-header): added config for default header components
  .github/workflows/link-checker.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  docs/dynamic-plugins/frontend-plugin-wiring.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/src/index.ts
  packages/app/package.json
  packages/app/src/components/DynamicRoot/CommonIcons.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/Root/ApplicationHeaders.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/Root/SidebarLogo.tsx
  yarn.lock
Labels: approved

#2410 fix: replace a dead link with a valid one
  docs/monitoring-and-logging.md
Labels: approved, lgtm, ok-to-test

#2416 fix: pod failed to start with notification plugin enabled (CrashLoopBackOff)
  dynamic-plugins.default.yaml
Labels: approved, lgtm

#2385 chore(e2e): techdocs addons tests
  .ibm/pipelines/value_files/sanity-check-plugins.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/techdocs.spec.ts
  e2e-tests/playwright/support/pages/catalog.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2359 chore: update bulk import plugins
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  e2e-tests/playwright/support/pages/bulk-import.ts
  yarn.lock
Labels: approved, lgtm

#2418 chore(ci): fix GH test where there is only one issue
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
Labels: approved, lgtm

#2423 chore: release-1.4: rollback bs scoped plugins to 1.4.0 levels
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  package.json
  yarn.lock
Labels: approved, lgtm

#2413 [release-1.5] feat(global-header): update header plugin and enable it by default
  .github/workflows/link-checker.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  app-config.dynamic-plugins.yaml
  docs/dynamic-plugins/frontend-plugin-wiring.md
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/.eslintrc.js
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/src/index.ts
  packages/app/package.json
  packages/app/src/components/DynamicRoot/CommonIcons.tsx
  packages/app/src/components/DynamicRoot/DynamicRootContext.tsx
  packages/app/src/components/Root/ApplicationHeaders.tsx
  packages/app/src/components/Root/Root.tsx
  packages/app/src/components/Root/SidebarLogo.tsx
  yarn.lock
Labels: approved, lgtm

#2426 chore(e2e): update owners for e2e-tests
  e2e-tests/OWNERS
Labels: approved, lgtm

#2417 chore(ci): fix sanity checks & re-enable audit-log for showcase
  .ibm/pipelines/cluster/aks/deployment.sh
  .ibm/pipelines/cluster/gke/deployment.sh
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
  e2e-tests/playwright.config.ts
Labels: approved, lgtm

#2430 chore(e2e): add new test project to Playwright config for flexibility
  e2e-tests/playwright.config.ts
Labels: lgtm

#2420 chore(ci): use branch specific operator version for e2e
  .ibm/pipelines/jobs/operator.sh
Labels: approved, lgtm

#2405 chore(e2e-test): [Test automation] Verify global floating action button , application provider and listener
  .ibm/pipelines/resources/config_map/dynamic-global-floating-action-button-config.yaml
  .ibm/pipelines/resources/config_map/dynamic-homepage-and-sidebar-config.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/e2e/home-page-customization.spec.ts
  e2e-tests/playwright/e2e/plugins/application-listener.spec.ts
  e2e-tests/playwright/e2e/plugins/application-provider.spec.ts
  e2e-tests/playwright/e2e/plugins/global-floating-button.spec.ts
  e2e-tests/playwright/support/pageObjects/global-fab-po.ts
  e2e-tests/playwright/support/pageObjects/page-obj.ts
  e2e-tests/playwright/support/pages/home-page.ts
Labels: approved, lgtm

#2437 fix: fix signout
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Labels: approved, lgtm

#2428 chore(ci): fix rsync interference & droute re-enable (#2414)
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2427 chore(ci): fix rsync interference & droute re-enable (#2414)
  .ibm/pipelines/utils.sh
Labels: approved, lgtm

#2434 chore(e2e): update smoke test to login as guest user
  e2e-tests/playwright/e2e/smoke-test.spec.ts
Labels: approved, lgtm

#2448 chore(e2e): add new test project configuration for generic test runs
  e2e-tests/playwright.config.ts
Labels: approved

#2354 fix: refactor authProviderModule and `dangerouslyAllowSignInWithoutUserInCatalog` config
  .yarn/patches/@backstage-plugin-auth-backend-module-atlassian-provider-npm-0.3.4-c82f4982c5.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-azure-easyauth-provider-npm-0.2.4-a2db8644ad.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-bitbucket-provider-npm-0.2.4-8521163175.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-bitbucket-server-provider-npm-0.1.4-49ea866e93.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-cloudflare-access-provider-npm-0.3.4-f0bd0e70b3.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-gcp-iap-provider-npm-0.3.4-8a91641643.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-github-provider-npm-0.2.4-ca975ad168.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-gitlab-provider-npm-0.2.4-8ff797ad5c.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-microsoft-provider-npm-0.2.4-002c0c3367.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-oauth2-proxy-provider-npm-0.2.4-a7c0682667.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-oidc-provider-npm-0.3.4-58f3083265.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-okta-provider-npm-0.1.4-6e105e61f8.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-onelogin-provider-npm-0.2.4-f2bab85a73.patch
  .yarn/patches/@backstage-plugin-auth-node-npm-0.5.6-3fad9202ca.patch
  docs/auth.md
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/utils/helper.ts
  package.json
  packages/app/config.d.ts
  packages/backend/package.json
  packages/backend/src/modules/authProvidersModule.test.ts
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/modules/authResolvers.ts
  scripts/rhdh-openshift-setup/resources/rhdh-configmap.yaml
  yarn.lock
Labels: approved, lgtm

#2453 [release-1.5] fix: refactor authProviderModule and dangerouslyAllowSignInWithoutUserInCatalog config
  .yarn/patches/@backstage-plugin-auth-backend-module-atlassian-provider-npm-0.3.4-c82f4982c5.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-azure-easyauth-provider-npm-0.2.4-a2db8644ad.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-bitbucket-provider-npm-0.2.4-8521163175.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-bitbucket-server-provider-npm-0.1.4-49ea866e93.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-cloudflare-access-provider-npm-0.3.4-f0bd0e70b3.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-gcp-iap-provider-npm-0.3.4-8a91641643.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-github-provider-npm-0.2.4-ca975ad168.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-gitlab-provider-npm-0.2.4-8ff797ad5c.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-microsoft-provider-npm-0.2.4-002c0c3367.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-oauth2-proxy-provider-npm-0.2.4-a7c0682667.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-oidc-provider-npm-0.3.4-58f3083265.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-okta-provider-npm-0.1.4-6e105e61f8.patch
  .yarn/patches/@backstage-plugin-auth-backend-module-onelogin-provider-npm-0.2.4-f2bab85a73.patch
  .yarn/patches/@backstage-plugin-auth-node-npm-0.5.6-3fad9202ca.patch
  docs/auth.md
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/utils/helper.ts
  package.json
  packages/app/config.d.ts
  packages/backend/package.json
  packages/backend/src/modules/authProvidersModule.test.ts
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/modules/authResolvers.ts
  scripts/rhdh-openshift-setup/resources/rhdh-configmap.yaml
  yarn.lock
Labels: approved, lgtm

#2445 test(e2e): fix rbac nightly test on 1.4
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2374 chore(e2e): update RBAC plugin version, add E2E tests to Showcase/RHDH
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  yarn.lock
Labels: approved, lgtm, ok-to-test

#2457 fix: fix e2e signout in auth providers tests
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
Labels: approved, lgtm

#2459 fix(init): proper floating tag support
  docker/install-dynamic-plugins.py
Labels: approved, lgtm

#2449 chore: release-1.4: rollback bs scoped plugins to 1.4.0 levels - REVERT
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-msgraph-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-notifications-backend-module-email-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-azure-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gerrit-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-gitlab-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-signals/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs-backend-dynamic/package.json
  dynamic-plugins/wrappers/backstage-plugin-techdocs/package.json
  package.json
  yarn.lock
Labels: approved, lgtm

#2447 chore: add SIGKILL note, add lock filename to log for waiting status
  docker/install-dynamic-plugins.py
  docs/dynamic-plugins/installing-plugins.md
Labels: approved, lgtm

#2412 chore(e2e): add e2e tests for global header
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/bulk-import.ts
  e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2454 chore(e2e): add e2e tests for header mount points
  .ibm/pipelines/resources/config_map/dynamic-global-header-config.yaml
  .ibm/pipelines/utils.sh
  .ibm/pipelines/value_files/values_showcase.yaml
  dynamic-plugins/_utils/src/wrappers.test.ts
  e2e-tests/playwright/e2e/header-mount-points.spec.ts
Labels: approved, lgtm

#2469 [release-1.5] chore(e2e): update RBAC plugin version, add E2E tests to Showcase/RHDH
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  yarn.lock
Labels: approved, lgtm

#2460 chore(ci): add Operator SDK into e2e-runner image
  .ibm/images/Dockerfile
Labels: approved, lgtm

#2472 [release-1.5] chore(e2e-tests): cherry pick global header e2e tests commits
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
  e2e-tests/playwright/e2e/authProviders/basic-authentication.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/microsoft-provider.spec.ts
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/google-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/guest-signin-happy-path.spec.ts
  e2e-tests/playwright/e2e/plugins/analytics/analytics-disabled-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/dynamic-plugins-info/dynamic-plugins-info.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
  e2e-tests/playwright/e2e/plugins/kubernetes-actions/kubernetes-actions.spec.ts
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/support/pages/bulk-import.ts
  e2e-tests/playwright/utils/custom-theme/theme-verifier.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2331 docs: add known issues doc with some workarounds
  docs/dynamic-plugins/export-derived-package.md
  docs/dynamic-plugins/known-issues.md
  docs/index.md
  packages/app/CHANGELOG.md
Labels: approved, lgtm, Stale
