Repository redhat-developer/rhdh, pull requests merged in 2025-04, with the labels that each got.

#2327 fix(fab): handle provider and listener crashes without interrupting the UI
  packages/app/src/components/Root/ApplicationListener.test.tsx
  packages/app/src/components/Root/ApplicationListener.tsx
  packages/app/src/components/Root/ApplicationProvider.test.tsx
  packages/app/src/components/Root/ApplicationProvider.tsx
Labels: approved, lgtm

#2665 chore: add SHORT_SHA handling and refine PR image tagging logic
  .github/actions/check-image-and-changes/action.yaml
  .github/workflows/pr-build-image.yaml
Labels: approved

#2667 chore(deps): update acr with backstage 1.36.1 upgrade
  dynamic-plugins/wrappers/backstage-community-plugin-acr/package.json
  yarn.lock
Labels: approved, lgtm

#2674 test: fix displayName null in auth-providers
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#2676 chore: fixed GH action Check Image and Relevant Changes
  .github/actions/check-image-and-changes/action.yaml
  .github/workflows/pr-build-image.yaml
Labels: approved, lgtm

#2685 chore(deps): bump to latest tar-fs 3.0.8 and 2.1.2 and dockerode 4.0.5; unfortunately older tar-fs 2.0.1 persists due to older deps like 2yr old dockerode 3.3 (CVE-2024-12905)
  yarn.lock
Labels: approved, lgtm

#2683 chore(deps): bump to latest tar-fs 3.0.8 and 2.1.2 (RHIDP-6744) (CVE-2024-12905)
  yarn.lock
Labels: approved, lgtm

#2684 chore: release-1.5: fix CVE-2024-12905
  yarn.lock
Labels: approved, lgtm

#2671 chore: declare GA support for GitHub scaffolder plugin
  dynamic-plugins/wrappers/backstage-plugin-scaffolder-backend-module-github-dynamic/package.json
Labels: approved, lgtm

#2704 chore(e2e): skip keycloak test
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
Labels: approved, lgtm

#2686 test: fix Github login in auth providers tests
  e2e-tests/playwright/utils/common.ts
Labels: approved, lgtm

#2694 chore: set default OIDC default resolver to resolve by sub claim
  e2e-tests/playwright/e2e/authProviders/rhsso-76-provider.spec.ts
  packages/backend/src/modules/authProvidersModule.ts
  packages/backend/src/modules/authResolvers.ts
Labels: approved, lgtm

#2698 chore(cachi2): clean up differences between...
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved

#2625 feat(marketplace): introduce the install page
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  yarn.lock
Labels: approved, lgtm

#2695 chore(nexus-repo-manager): update package version
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  yarn.lock
Labels: approved, lgtm

#2714 chore(nexus-repo-manager): update package version
  dynamic-plugins/wrappers/backstage-community-plugin-nexus-repository-manager/package.json
  yarn.lock
Labels: approved, lgtm

#2691 chore(e2e): e2e for sidebar config to hide
  .ibm/pipelines/resources/config_map/dynamic-plugins-config.yaml
  e2e-tests/playwright/e2e/plugins/frontend/sidebar.spec.ts
Labels: approved, lgtm

#2577 fix(marketplace): add MUI v5 workaround to marketplace wrapper, similar to other plugins
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/src/index.ts
  yarn.lock
Labels: approved, lgtm

#2716 chore(jfrog-artifactory): update package version
  dynamic-plugins/wrappers/backstage-community-plugin-jfrog-artifactory/package.json
  yarn.lock
Labels: approved, lgtm

#2718 chore(e2e): fix rbac test failure due to animation
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
Labels: approved, lgtm

#2719 chore(e2e): set keycloak signIn resolver on deployments
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
Labels: approved, lgtm

#2724 chore(e2e-tests): exclude e2e-tests folder from .rhdh dockerfile (RHIDP-6868)
  .rhdh/docker/Dockerfile
  scripts/update-Dockerfile.sh
Labels: approved

#2727 chore: move python deps into python/ folder; use in both up and downstream docker files (RHIDP-6561)
  .rhdh/docker/Dockerfile
  .rhdh/docker/README.requirements.md
  docker/Dockerfile
  python/README.requirements.md
  python/requirements-build.in
  python/requirements-build.txt
  python/requirements.in
  python/requirements.txt
  python/setup.py
Labels: approved, lgtm

#2743 chore: add renovate config to ignore zod updates
  .github/renovate.json
Labels: approved, lgtm

#2737 [release-1.6] chore: update plugin wrappers
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/src/index.ts
  e2e-tests/playwright/e2e/plugins/global-floating-button.spec.ts
  yarn.lock
Labels: approved, lgtm

#2742 [release-1.6] chore(theme): cherry pick theme update
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#2748 chore(dockerfile): suppress 'dubious...
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved

#2763 fix(api-docs): use plugin-catalog from backstage 1.36.1
  yarn.lock
Labels: lgtm

#2677 feat(e2e): add keycloak metrics test
  .ibm/pipelines/resources/config_map/app-config-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
  e2e-tests/playwright/utils/kube-client.ts
Labels: approved, lgtm

#2697 chore(e2e): add tests for rbac tests for the kubernetes plugin
  .ibm/pipelines/env_variables.sh
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/playwright.config.ts
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/e2e/plugins/kubernetes/kubernetes-rbac.spec.ts
  e2e-tests/playwright/support/pageObjects/page-obj.ts
  e2e-tests/playwright/support/pages/kubernetes.ts
Labels: approved, lgtm

#2756 feat(wrappers): update tekton, argocd, home-page
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  yarn.lock
Labels: approved, lgtm

#2765 chore(deps): update the RBAC plugins
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  packages/app/package.json
  packages/app/src/components/Root/Root.tsx
  packages/backend/package.json
  plugins/licensed-users-info-backend/package.json
  scripts/rhdh-openshift-setup/resources/rbac-policies.yaml
  yarn.lock
Labels: approved, lgtm

#2762 feat(wrappers): update tekton, argocd, home-page
  dynamic-plugins/wrappers/backstage-community-plugin-redhat-argocd/package.json
  dynamic-plugins/wrappers/backstage-community-plugin-tekton/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-dynamic-home-page/package.json
  yarn.lock
Labels: approved, lgtm

#2751 [release-1.6] chore: update bulk-import frontend, global-fab, global-header and marketplace plugins
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-bulk-import/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-floating-action-button/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-global-header/package.json
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  e2e-tests/playwright/e2e/default-global-header.spec.ts
  e2e-tests/playwright/e2e/extensions.spec.ts
  e2e-tests/playwright/support/pages/extensions.ts
  yarn.lock
Labels: lgtm

#2771 [release-1.6] chore(deps): update the RBAC plugins
  .ibm/pipelines/resources/config_map/rbac-policy.csv
  dynamic-plugins/wrappers/backstage-community-plugin-rbac/package.json
  e2e-tests/playwright/data/rbac-constants.ts
  e2e-tests/playwright/utils/authenticationProviders/constants.ts
  packages/app/package.json
  packages/app/src/components/Root/Root.tsx
  packages/backend/package.json
  plugins/licensed-users-info-backend/package.json
  scripts/rhdh-openshift-setup/resources/rbac-policies.yaml
  yarn.lock
Labels: approved, lgtm

#2769 chore(e2e): update upgrade e2e test by bump up the base version to 1.5
  .ibm/pipelines/jobs/upgrade.sh
  .ibm/pipelines/value_files/values_showcase_1.4.yaml
  .ibm/pipelines/value_files/values_showcase_1.5.yaml
Labels: approved

#2687 test(topology): introduce e2e tests for Topology with RBAC
  .ibm/pipelines/resources/config_map/app-config-rhdh-rbac.yaml
  .ibm/pipelines/value_files/values_showcase-rbac.yaml
  e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology-rbac.spec.ts
  e2e-tests/playwright/e2e/plugins/topology/topology.spec.ts
  e2e-tests/playwright/support/pageObjects/rbac-po.ts
  e2e-tests/playwright/support/pages/rbac.ts
  e2e-tests/playwright/support/pages/topology.ts
  e2e-tests/playwright/utils/helper.ts
Labels: approved, lgtm

#2741 fix(theme): fix outline button on bulk import add page and extensions install page
  packages/app/package.json
  yarn.lock
Labels: approved, lgtm

#2773 chore(e2e): cherry-pick quay test fix from main into 1.5 release from PR#2383
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
Labels: approved, lgtm

#2785 feat(e2e): increase route timeout for keycloak metrics
  e2e-tests/playwright/e2e/plugins/keycloak/catalog-users.spec.ts
Labels: approved, lgtm

#2778 [release-1.5] fix(extensions): update package version strings displayed in extensions ui
  catalog-entities/marketplace/packages/backstage-community-plugin-azure-devops-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-azure-devops.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-keycloak.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-catalog-backend-module-pingidentity.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-dynatrace.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-github-actions.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-github-issues.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-jenkins-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-jenkins.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-lighthouse.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-scaffolder-backend-module-quay.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-sonarqube-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-sonarqube.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar-backend.yaml
  catalog-entities/marketplace/packages/backstage-community-plugin-tech-radar.yaml
  catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab-backend.yaml
  catalog-entities/marketplace/packages/immobiliarelabs-backstage-plugin-gitlab.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-catalog-backend-module-m.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-global-floating-action-b.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace-backend.yaml
  catalog-entities/marketplace/packages/red-hat-developer-hub-backstage-plugin-marketplace.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-argo-cd.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-datadog.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-insights.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-github-pull-requests.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-jira.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-security-insights.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-argocd.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-http-request.yaml
  catalog-entities/marketplace/packages/roadiehq-scaffolder-backend-module-utils.yaml
Labels: approved, lgtm

#2788 fix(extensions): add or update some catalog icons
  catalog-entities/marketplace/plugins/1-boilerplate.yaml.sample
  catalog-entities/marketplace/plugins/analytics-provider-segment.yaml
  catalog-entities/marketplace/plugins/catalog-integrations.yaml
  catalog-entities/marketplace/plugins/global-header.yaml
  catalog-entities/marketplace/plugins/http-request-scaffolder-action.yaml
  catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml
  catalog-entities/marketplace/plugins/microsoft-graph-catalog-integration.yaml
  catalog-entities/marketplace/plugins/notifications-email.yaml
  catalog-entities/marketplace/plugins/notifications.yaml
  catalog-entities/marketplace/plugins/openshift-cluster-manager.yaml
  catalog-entities/marketplace/plugins/orchestrator.yaml
  catalog-entities/marketplace/plugins/pingidentity.yaml
  catalog-entities/marketplace/plugins/regex-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/roadie-scaffolder-util-actions.yaml
  catalog-entities/marketplace/plugins/scaffolder-integrations.yaml
  catalog-entities/marketplace/plugins/servicenow-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/signals-backend.yaml
  catalog-entities/marketplace/plugins/signals.yaml
  catalog-entities/marketplace/plugins/techdocs.yaml
Labels: approved, lgtm

#2789 fix(extensions): show a no-icon-icon when the icon is missing in the plugin metadata
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace/package.json
  yarn.lock
Labels: approved, lgtm

#2699 chore(e2e): update e2e tests by enabling and refining scaffold log validations
  .ibm/pipelines/jobs/operator.sh
  .ibm/pipelines/utils.sh
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
  e2e-tests/playwright/e2e/audit-log/scaffold.spec.ts
Labels: approved, lgtm, Stale

#2652 feat(theme): replace theme package with rhdh-plugins theme plugin
  packages/app/package.json
  packages/app/src/components/DynamicRoot/DynamicRoot.tsx
  packages/app/src/components/DynamicRoot/Loader.tsx
  yarn.lock
Labels: approved, lgtm

#2802 chore(deps): add missing dependency from backstage-plugin-marketplace-backend 0.3 to backstage-plugin-marketplace-common 0.3.0 (RHIDP-6964) [release-1.6]
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2801 chore(deps): add missing dependency from backstage-plugin-marketplace-backend 0.3 to backstage-plugin-marketplace-common 0.3.0 (RHIDP-6964) [main]
  dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic/package.json
  yarn.lock
Labels: approved, lgtm

#2793 fix(extensions): update some catalog metadata
  catalog-entities/marketplace/plugins/ansible-plugin.yaml
  catalog-entities/marketplace/plugins/argocd-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/azure-container-registry.yaml
  catalog-entities/marketplace/plugins/azure-devops.yaml
  catalog-entities/marketplace/plugins/azure-repositories.yaml
  catalog-entities/marketplace/plugins/azure-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/backstage-community-plugin-quay.yaml
  catalog-entities/marketplace/plugins/bitbucket-cloud-catalog-integration.yaml
  catalog-entities/marketplace/plugins/bitbucket-cloud-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/bitbucket-server-catalog-integration.yaml
  catalog-entities/marketplace/plugins/bitbucket-server-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/bulk-import.yaml
  catalog-entities/marketplace/plugins/datadog.yaml
  catalog-entities/marketplace/plugins/dynatrace-commercial.yaml
  catalog-entities/marketplace/plugins/extensions.yaml
  catalog-entities/marketplace/plugins/gerrit-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/github-actions.yaml
  catalog-entities/marketplace/plugins/gitlab-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/http-request-scaffolder-action.yaml
  catalog-entities/marketplace/plugins/kubernetes-backend.yaml
  catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml
  catalog-entities/marketplace/plugins/microsoft-graph-catalog-integration.yaml
  catalog-entities/marketplace/plugins/pingidentity.yaml
  catalog-entities/marketplace/plugins/redhat-argocd.yaml
  catalog-entities/marketplace/plugins/regex-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/roadie-scaffolder-util-actions.yaml
  catalog-entities/marketplace/plugins/servicenow-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/signals-backend.yaml
  catalog-entities/marketplace/plugins/signals.yaml
  catalog-entities/marketplace/plugins/sonarqube-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/techdocs.yaml
  catalog-entities/marketplace/plugins/tekton.yaml
  catalog-entities/marketplace/plugins/topology.yaml
Labels: approved, lgtm

#2795 chore(e2e): topology-rbac test skipped
  e2e-tests/playwright/e2e/plugins/topology/topology-rbac.spec.ts
Labels: approved, lgtm

#2805 fix(extensions): update some catalog icons (again)
  catalog-entities/marketplace/plugins/3scale.yaml
  catalog-entities/marketplace/plugins/analytics-provider-segment.yaml
  catalog-entities/marketplace/plugins/ansible-plugin.yaml
  catalog-entities/marketplace/plugins/argocd-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/azure-devops.yaml
  catalog-entities/marketplace/plugins/azure-repositories.yaml
  catalog-entities/marketplace/plugins/azure-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/bitbucket-cloud-catalog-integration.yaml
  catalog-entities/marketplace/plugins/bitbucket-cloud-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/bitbucket-server-catalog-integration.yaml
  catalog-entities/marketplace/plugins/bitbucket-server-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/catalog-integrations.yaml
  catalog-entities/marketplace/plugins/datadog.yaml
  catalog-entities/marketplace/plugins/gerrit-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/github-actions.yaml
  catalog-entities/marketplace/plugins/github-catalog-integration.yaml
  catalog-entities/marketplace/plugins/github-insights.yaml
  catalog-entities/marketplace/plugins/github-issues.yaml
  catalog-entities/marketplace/plugins/github-pull-requests.yaml
  catalog-entities/marketplace/plugins/github-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/gitlab-catalog-cards.yaml
  catalog-entities/marketplace/plugins/gitlab-catalog-integration.yaml
  catalog-entities/marketplace/plugins/gitlab-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/global-header.yaml
  catalog-entities/marketplace/plugins/http-request-scaffolder-action.yaml
  catalog-entities/marketplace/plugins/jenkins.yaml
  catalog-entities/marketplace/plugins/jfrog-artifactory.yaml
  catalog-entities/marketplace/plugins/jira.yaml
  catalog-entities/marketplace/plugins/keycloak-catalog-integration.yaml
  catalog-entities/marketplace/plugins/kubernetes-backend.yaml
  catalog-entities/marketplace/plugins/kubernetes-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/kubernetes.yaml
  catalog-entities/marketplace/plugins/ldap-catalog-integration.yaml
  catalog-entities/marketplace/plugins/lighthouse.yaml
  catalog-entities/marketplace/plugins/microsoft-graph-catalog-integration.yaml
  catalog-entities/marketplace/plugins/nexus-repository-manager.yaml
  catalog-entities/marketplace/plugins/notifications-email.yaml
  catalog-entities/marketplace/plugins/notifications.yaml
  catalog-entities/marketplace/plugins/pagerduty.yaml
  catalog-entities/marketplace/plugins/pingidentity.yaml
  catalog-entities/marketplace/plugins/quay-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/redhat-argocd.yaml
  catalog-entities/marketplace/plugins/roadie-argocd.yaml
  catalog-entities/marketplace/plugins/roadie-scaffolder-util-actions.yaml
  catalog-entities/marketplace/plugins/scaffolder-integrations.yaml
  catalog-entities/marketplace/plugins/security-insights.yaml
  catalog-entities/marketplace/plugins/servicenow-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/signals-backend.yaml
  catalog-entities/marketplace/plugins/signals.yaml
  catalog-entities/marketplace/plugins/sonarqube-catalog-cards.yaml
  catalog-entities/marketplace/plugins/sonarqube-scaffolder-actions.yaml
  catalog-entities/marketplace/plugins/tech-radar.yaml
  catalog-entities/marketplace/plugins/techdocs.yaml
  catalog-entities/marketplace/plugins/tekton.yaml
Labels: approved, lgtm

#2747 chore(e2e): fix the flaky filter issue on catalog page
  e2e-tests/playwright/e2e/audit-log/catalog.spec.ts
  e2e-tests/playwright/e2e/authProviders/github-happy-path.spec.ts
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/plugins/acr.spec.ts
  e2e-tests/playwright/e2e/plugins/quay/quay.spec.ts
  e2e-tests/playwright/support/pages/catalog.ts
  e2e-tests/playwright/utils/ui-helper.ts
Labels: approved, lgtm

#2803 chore(docker): update dockerfiles based on Stan's fix and Tomas' validation - RHIDP-6964 [main]
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved

#2804 chore(docker): update dockerfiles based on Stan's fix and Tomas' validation - RHIDP-6964 [release-1.6]
  .rhdh/docker/Dockerfile
  docker/Dockerfile
Labels: approved

#2800 feat: remove the ArgoCD frontend plugin from RoadieHQ
  .github/renovate.json
  .ibm/pipelines/value_files/diff-values_showcase-sanity-plugins.yaml
  .rhdh/docker/Dockerfile
  README.md
  app-config.dynamic-plugins.yaml
  catalog-entities/marketplace/packages/all.yaml
  catalog-entities/marketplace/packages/roadiehq-backstage-plugin-argo-cd.yaml
  catalog-entities/marketplace/plugins/roadie-argocd.yaml
  docker/Dockerfile
  dynamic-plugins.default.yaml
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/.eslintignore
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/.eslintrc.js
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/package.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/src/index.ts
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/tsconfig.json
  dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd/turbo.json
  plugins/dynamic-plugins-info/src/components/InternalPluginsMap.ts
  yarn.lock
Labels: approved, lgtm

#2710 chore(e2e): skip tests in osd gcp nightly job affected due to RHIDP-5704
  e2e-tests/playwright/e2e/catalog-scaffolded-from-link.spec.ts
  e2e-tests/playwright/e2e/catalog-timestamp.spec.ts
  e2e-tests/playwright/e2e/github-integration-org-fetch.spec.ts
  e2e-tests/playwright/e2e/plugins/http-request.spec.ts
Labels: approved, lgtm
